Repository Dungeon-CampusMinden/Dungeon, pull requests merged in 2022-12, with the labels that each got.

#80 [GAME] Add documentation and refactor code
  game/src/room/RoomGenerator.java
Labels: documentation

#78 [DSL->GAME] Prototype for native function call
  checks.xml
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/interpreter/dot/Interpreter.java
  dsl/src/parser/AST/AstVisitor.java
  dsl/src/parser/AST/FuncCallNode.java
  dsl/src/parser/AST/Node.java
  dsl/src/parser/AST/NumNode.java
  dsl/src/parser/AST/ObjectDefNode.java
  dsl/src/parser/AST/PropertyDefNode.java
  dsl/src/parser/AST/StringNode.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/runtime/MemorySpace.java
  dsl/src/runtime/Value.java
  dsl/src/runtime/nativeFunctions/NativePrint.java
  dsl/src/symboltable/AggregateType.java
  dsl/src/symboltable/BuiltInType.java
  dsl/src/symboltable/FunctionCallResolver.java
  dsl/src/symboltable/FunctionSymbol.java
  dsl/src/symboltable/ICallable.java
  dsl/src/symboltable/IScope.java
  dsl/src/symboltable/IType.java
  dsl/src/symboltable/Scope.java
  dsl/src/symboltable/ScopedSymbol.java
  dsl/src/symboltable/Symbol.java
  dsl/src/symboltable/SymbolTable.java
  dsl/src/symboltable/SymbolTableParser.java
  dsl/src/symboltable/VariableBinder.java
  dsl/test/helpers/Helpers.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/interpreter/dot/TestDotInterpreter.java
  dsl/test/parser/TestDungeonASTConverter.java
  dsl/test/symboltable/TestSymbolTableParser.java
  game/test/graph/TestGraphs.java
Labels: enhancement

#104 Fix setting of Value.NULL
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/runtime/MemorySpace.java
  dsl/src/runtime/Value.java
  dsl/test/interpreter/TestDSLInterpreter.java
Labels: bug

#93 [GAME] JUnit Tests für ECS
  game/src/ecs/components/AnimationComponent.java
  game/src/ecs/components/PlayableComponent.java
  game/src/ecs/components/VelocityComponent.java
  game/src/ecs/systems/KeyboardSystem.java
  game/src/ecs/systems/MovementSystem.java
  game/test/ecs/components/AnimationComponentTest.java
  game/test/ecs/components/PlayableComponentTest.java
  game/test/ecs/components/PositionComponentTest.java
  game/test/ecs/components/VelocityComponentTest.java
  game/test/ecs/systems/DrawSystemTest.java
  game/test/ecs/systems/MovementSystemTest.java
Labels: enhancement

#106 [GAME] Hero und Steuerung
  game/src/ecs/components/AnimationComponent.java
  game/src/ecs/components/PlayableComponent.java
  game/src/ecs/components/PositionComponent.java
  game/src/ecs/components/VelocityComponent.java
  game/src/ecs/entitys/Hero.java
  game/src/ecs/systems/DrawSystem.java
  game/src/ecs/systems/ECS_System.java
  game/src/ecs/systems/KeyboardSystem.java
  game/src/ecs/systems/MovementSystem.java
  game/src/ecs/systems/SystemController.java
  game/src/mydungeon/ECS.java
  game/test/ecs/components/AnimationComponentTest.java
  game/test/ecs/components/PlayableComponentTest.java
  game/test/ecs/components/PositionComponentTest.java
  game/test/ecs/components/VelocityComponentTest.java
  game/test/ecs/systems/DrawSystemTest.java
  game/test/ecs/systems/MovementSystemTest.java
Labels: enhancement, SHK

#107 Rename symboltable package to semantic analysis
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/runtime/MemorySpace.java
  dsl/src/runtime/Value.java
  dsl/src/runtime/nativeFunctions/NativePrint.java
  dsl/src/semanticAnalysis/FunctionCallResolver.java
  dsl/src/semanticAnalysis/FunctionSymbol.java
  dsl/src/semanticAnalysis/ICallable.java
  dsl/src/semanticAnalysis/IScope.java
  dsl/src/semanticAnalysis/Scope.java
  dsl/src/semanticAnalysis/ScopedSymbol.java
  dsl/src/semanticAnalysis/Symbol.java
  dsl/src/semanticAnalysis/SymbolTable.java
  dsl/src/semanticAnalysis/SymbolTableParser.java
  dsl/src/semanticAnalysis/VariableBinder.java
  dsl/src/semanticAnalysis/types/AggregateType.java
  dsl/src/semanticAnalysis/types/BuiltInType.java
  dsl/src/semanticAnalysis/types/DSLType.java
  dsl/src/semanticAnalysis/types/DSLTypeMember.java
  dsl/src/semanticAnalysis/types/IType.java
  dsl/src/semanticAnalysis/types/TypeBuilder.java
  dsl/test/helpers/Helpers.java
  dsl/test/semanticAnalysis/TestSymbolTableParser.java
  dsl/test/semanticAnalysis/types/TestTypeBuilder.java
  game/src/dslToGame/TestComponent.java
Labels: enhancement

#108 Add annotation based TypeBuilder
  dsl/src/semanticAnalysis/SymbolTableParser.java
  dsl/src/semanticAnalysis/typebulder/TypeBuilder.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/semanticAnalysis/typebuilder/TestTypeBuilder.java
  game/src/dslToGame/QuestConfig.java
  game/src/quest/GraphSearchQuest.java
  game/src/quest/Quest.java
Labels: enhancement

#109 Add environments to store types and function definitions
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/runtime/GameEnvironment.java
  dsl/src/runtime/IEvironment.java
  dsl/src/runtime/nativeFunctions/NativePrint.java
  dsl/src/semanticAnalysis/IScope.java
  dsl/src/semanticAnalysis/ScopedSymbol.java
  dsl/src/semanticAnalysis/SymbolTableParser.java
  dsl/test/helpers/Helpers.java
Labels: enhancement
