Repository Dungeon-CampusMinden/Dungeon, pull requests merged in 2022-11, with the labels that each got.

#31 [GAME] Hitbox System verbessern
  code/game/src/character/DungeonCharacter.java
  code/game/src/character/monster/Imp.java
  code/game/src/character/monster/Monster.java
  code/game/src/character/player/Hero.java
  code/game/src/collision/Collidable.java
  code/game/src/collision/CollisionMap.java
  code/game/src/collision/Hitbox.java
  code/game/src/collision/RectCollidable.java
  code/game/src/collision/TileCollidable.java
  code/game/src/mydungeon/Starter.java
Labels: high prio, SHK

#51 Add dot graph parser
  build.gradle
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/interpreter/Interpreter.java
  dsl/src/interpreter/dot/Interpreter.java
  dsl/src/parser/AST/AstVisitor.java
  dsl/src/parser/AST/BinaryNode.java
  dsl/src/parser/AST/DotDefNode.java
  dsl/src/parser/AST/EdgeOpNode.java
  dsl/src/parser/AST/EdgeRhsNode.java
  dsl/src/parser/AST/EdgeStmtNode.java
  dsl/src/parser/AST/IdNode.java
  dsl/src/parser/AST/Node.java
  dsl/src/parser/AST/SourceFileReference.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/test/helpers/Helpers.java
  dsl/test/interpreter/dot/TestDotInterpreter.java
  dsl/test/parser/TestDungeonASTConverter.java
  game/src/graph/Edge.java
  game/src/graph/Graph.java
  game/src/graph/Node.java
Labels: enhancement

#59 [GAME] Added treasure chest
  game/src/character/objects/Item.java
  game/src/character/objects/TreasureChest.java
  game/src/mydungeon/Starter.java
Labels: enhancement, SHK

#58 Add CI
  .github/workflows/github_ci.yml
Labels: enhancement

#65 Call gradle spotlessApply
  game/src/character/objects/TreasureChest.java
  game/src/mydungeon/Starter.java
Labels: bug

#66 set execution flag on gradlew
  gradle/wrapper/gradle-wrapper.jar
  gradlew
Labels: bug

#61 [DSL->Game] Handoff
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/interpreter/dot/Interpreter.java
  dsl/test/interpreter/TestDSLInterpreter.java
  game/src/dslToGame/QuestConfig.java
Labels: enhancement

#67 add treasureChest texture
  game/assets/objects/treasurechest/chest_empty_open_anim_f2.png
  game/assets/objects/treasurechest/chest_full_open_anim_f0.png
  game/assets/objects/treasurechest/chest_full_open_anim_f1.png
  game/assets/objects/treasurechest/chest_full_open_anim_f2.png
  game/src/character/objects/TreasureChest.java
  game/src/mydungeon/Starter.java
Labels: enhancement

#62 [GAME] Letter Item implemented
  game/src/character/objects/Letter.java
  game/src/character/objects/TreasureChest.java
  game/src/minimap/IMinimap.java
  game/src/mydungeon/Starter.java
Labels: enhancement, SHK

#68 update framework version to 5.1.0
  build.gradle
Labels: enhancement

#72 Change import level.elements.Tile to level.elements.tile.Tile
  game/src/character/monster/Monster.java
  game/src/collision/CollisionMap.java
  game/src/collision/TileCollidable.java
Labels: bug

#75 [GAME] Password Chest
  game/assets/hud/white.png
  game/src/character/objects/PasswordChest.java
  game/src/character/objects/PasswordInputUI.java
  game/src/character/objects/TreasureChest.java
  game/src/mydungeon/Starter.java
Labels: enhancement, SHK

#73 [DRAFT] [DSL] QuestConfig Parsing
  build.gradle
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/interpreter/dot/Interpreter.java
  dsl/src/parser/AST/AstVisitor.java
  dsl/src/parser/AST/Node.java
  dsl/src/parser/AST/NumNode.java
  dsl/src/parser/AST/ObjectDefNode.java
  dsl/src/parser/AST/PropertyDefNode.java
  dsl/src/parser/AST/StringNode.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/symboltable/AggregateType.java
  dsl/src/symboltable/BuiltInType.java
  dsl/src/symboltable/IScope.java
  dsl/src/symboltable/IType.java
  dsl/src/symboltable/Scope.java
  dsl/src/symboltable/ScopedSymbol.java
  dsl/src/symboltable/Symbol.java
  dsl/src/symboltable/SymbolTable.java
  dsl/src/symboltable/SymbolTableParser.java
  dsl/src/symboltable/VariableBinder.java
  dsl/test/helpers/Helpers.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/parser/TestDungeonASTConverter.java
  dsl/test/symboltable/TestSymbolTableParser.java
  dsl/test_resources/program.ds
  game/src/dslToGame/QuestConfig.java
  game/src/dslToGame/QuestConfigBuilder.java
Labels: enhancement

#57 Graphensuche (feiner PoC)
  build.gradle
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/interpreter/dot/Interpreter.java
  dsl/src/parser/AST/AstVisitor.java
  dsl/src/parser/AST/Node.java
  dsl/src/parser/AST/NumNode.java
  dsl/src/parser/AST/ObjectDefNode.java
  dsl/src/parser/AST/PropertyDefNode.java
  dsl/src/parser/AST/StringNode.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/symboltable/AggregateType.java
  dsl/src/symboltable/BuiltInType.java
  dsl/src/symboltable/IScope.java
  dsl/src/symboltable/IType.java
  dsl/src/symboltable/Scope.java
  dsl/src/symboltable/ScopedSymbol.java
  dsl/src/symboltable/Symbol.java
  dsl/src/symboltable/SymbolTable.java
  dsl/src/symboltable/SymbolTableParser.java
  dsl/src/symboltable/VariableBinder.java
  dsl/test/helpers/Helpers.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/parser/TestDungeonASTConverter.java
  dsl/test/symboltable/TestSymbolTableParser.java
  dsl/test_resources/program.ds
  game/assets/scripts/input1.ds
  game/src/character/objects/Letter.java
  game/src/character/objects/PasswordChest.java
  game/src/dslToGame/ConvertedGraph.java
  game/src/dslToGame/DotToLevelGraph.java
  game/src/dslToGame/QuestConfig.java
  game/src/dslToGame/QuestConfigBuilder.java
  game/src/levelgraph/DoorDirection.java
  game/src/levelgraph/GraphLevel.java
  game/src/levelgraph/GraphLevelGenerator.java
  game/src/levelgraph/LevelNode.java
  game/src/minimap/IMinimap.java
  game/src/minimap/TextMap.java
  game/src/mydungeon/Starter.java
  game/src/quest/Evaluateable.java
  game/src/quest/GraphSearchQuest.java
  game/src/quest/Quest.java
  game/src/quest/QuestFactory.java
  game/src/room/IRoom.java
  game/src/room/Room.java
  game/src/room/RoomGenerator.java
Labels: enhancement
