Repository Dungeon-CampusMinden/Dungeon, pull requests merged in 2023-08, with the labels that each got.

#918 [Game] Fix texture path of items
  game/assets/items/book/letter.png
  game/assets/items/book/magic_scroll.png
  game/assets/items/book/red_book.png
  game/assets/items/book/spell_book.png
  game/assets/items/book/wisdom_scroll.png
  game/src/contrib/utils/components/item/Item.java
Labels: bug, struct:dungeon

#904 [DSL] Single- und Multiple-Choice Fragen per DSL definieren
  build.gradle
  doc/tasks/anleitung_task_test.md
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/runtime/EncapsulatedObject.java
  dsl/src/runtime/GameEnvironment.java
  dsl/src/runtime/ListValue.java
  dsl/src/runtime/MemorySpace.java
  dsl/src/runtime/RuntimeObjectTranslator.java
  dsl/src/runtime/SetValue.java
  dsl/src/semanticanalysis/SemanticAnalyzer.java
  dsl/src/semanticanalysis/types/TypeBuilder.java
  dsl/src/semanticanalysis/types/TypeInstantiator.java
  dsl/src/semanticanalysis/types/callbackadapter/BiFunctionCallbackAdapter.java
  dsl/src/semanticanalysis/types/callbackadapter/BiFunctionFunctionTypeBuilder.java
  dsl/src/semanticanalysis/types/callbackadapter/CallbackAdapter.java
  dsl/src/semanticanalysis/types/callbackadapter/CallbackAdapterBuilder.java
  dsl/src/semanticanalysis/types/callbackadapter/FunctionCallbackAdapter.java
  dsl/test/helpers/Helpers.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/semanticanalysis/TestTypeBinder.java
  dsl/test/semanticanalysis/types/TestTypeBuilder.java
  dsl/test/semanticanalysis/types/TestTypeInstantiator.java
  dungeon/assets/scripts/task_test.dng
  dungeon/src/dslToGame/QuestConfig.java
  dungeon/src/dslToGame/taskdsltypes/MultipleChoiceTask.java
  dungeon/src/dslToGame/taskdsltypes/SingleChoiceTask.java
  dungeon/src/task/Task.java
  dungeon/src/task/quizquestion/Quiz.java
  dungeon/src/task/quizquestion/UIAnswerCallback.java
  dungeon/test/dslToGame/TestRuntimeObjectTranslator.java
  dungeon/test/manual/quizquestion/WizardQuizTest.java
  dungeon/test/manual/taskgeneration/TaskGenerationTest.java
Labels: struct:dungeon, struct:dsl

#919 [Game] fix: Healthbars misalign on window rescale due to missing window to stage coordinate conversion
  game/src/contrib/systems/HealthbarSystem.java
Labels: bug, staff:shk, struct:dungeon

#928 [DSL] Interpretation von Member-Zugriff implementieren
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/runtime/EncapsulatedObject.java
  dsl/src/semanticanalysis/FunctionCallResolver.java
  dsl/src/semanticanalysis/FunctionDefinitionBinder.java
  dsl/src/semanticanalysis/IScope.java
  dsl/src/semanticanalysis/SemanticAnalyzer.java
  dsl/src/semanticanalysis/types/TypeBuilder.java
  dsl/test/helpers/Helpers.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/interpreter/mockecs/TestComponentStringMemberAndCallback.java
  dsl/test/semanticanalysis/TestSemanticAnalyzer.java
Labels: struct:dsl

#933 [DSL] Implementieren von `getConfigs`
  dsl/src/interpreter/DSLEntryPointFinder.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/test/interpreter/TetsDSLEntryPointFinder.java
  dsl/test_resources/config1.dng
  dsl/test_resources/config2.dng
  dungeon/src/dslToGame/DSLEntryPoint.java
  dungeon/src/dslToGame/ParsedFile.java
  dungeon/src/dslToGame/QuestConfig.java
Labels: struct:dsl

#920 [GAME] ProtectOnAttack `peek` vs `filter` überarbeitet
  game/src/contrib/utils/components/ai/transition/ProtectOnAttack.java
Labels: staff:shk, struct:dungeon

#937 [GAME] add chance for DesignLabel to get picked
  game/src/core/level/utils/DesignLabel.java
Labels: struct:dungeon

#936 [Game] Verbesserung der Bewegung im Dungeon
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/utils/components/skill/FireballSkill.java
  game/src/core/level/Tile.java
  game/src/core/systems/VelocitySystem.java
  game/src/core/utils/Constants.java
  game/test/core/systems/VelocitySystemTest.java
Labels: staff:shk, struct:dungeon

#402 [DSL] Dokumentation zu Sprachkonzepten
  doc/dsl/semantische-analyse.md
  doc/dsl/sprachkonzepte.md
Labels: struct:documentation

#934 [Game] add InventoryGUI
  game/assets/skin/myFont.png
  game/src/contrib/components/InventoryComponent.java
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/hud/CombinableGUI.java
  game/src/contrib/hud/GUICombination.java
  game/src/contrib/hud/inventory/InventoryGUI.java
  game/src/contrib/hud/inventory/ItemDragPayload.java
  game/src/contrib/utils/components/health/DropLoot.java
  game/src/contrib/utils/components/interaction/DropItemsInteraction.java
  game/src/contrib/utils/components/item/Item.java
  game/src/core/Game.java
  game/src/core/systems/HudSystem.java
  game/test/contrib/components/InventoryComponentTest.java
  game/test/contrib/entities/ChestTest.java
  game/test/contrib/utils/components/item/ItemDataTest.java
Labels: staff:shk, struct:dungeon

#947 [DUNGEON] add `jarConverter.sh` to create Jar Files
  doc/jar_converter/readme.md
  jarConverter.sh
Labels: staff:wimi, struct:deployment

#963 [Game] Kisten haben ein Inventar, statt die Items fallen zu lassen
  game/src/contrib/entities/EntityFactory.java
Labels: staff:shk, struct:dungeon

#960 [GAME] add `PositionSystem`
  game/src/core/Game.java
  game/src/core/components/PositionComponent.java
  game/src/core/systems/PositionSystem.java
  game/src/core/utils/Point.java
  game/test/core/systems/PositionSystemTest.java
Labels: struct:dungeon

#942 [GAME] use map `Set<EntiteSystemMapper>` with `ILevel` to create a link between the level and the entities
  dungeon/test/manual/dslFileReader/DslFileReaderTest.java
  dungeon/test/manual/quizquestion/CallbackTest.java
  dungeon/test/manual/taskgeneration/TaskGenerationTest.java
  game/src/core/Game.java
  game/src/starter/Main.java
Labels: staff:wimi, struct:dungeon

#954 [Game] Add Crafting GUI
  game/assets/hud/button/button_hover.png
  game/assets/hud/button/button_idle.png
  game/assets/hud/button/button_press.png
  game/assets/hud/check.png
  game/assets/hud/crafting/background.png
  game/assets/hud/cross.png
  game/assets/objects/cauldron/idle/cauldron_0.png
  game/assets/recipes/steel_0.recipe
  game/src/contrib/crafting/Crafting.java
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/entities/WorldItemBuilder.java
  game/src/contrib/hud/Button.java
  game/src/contrib/hud/CombinableGUI.java
  game/src/contrib/hud/GUICombination.java
  game/src/contrib/hud/ImageButton.java
  game/src/contrib/hud/crafting/CraftingGUI.java
  game/src/contrib/hud/inventory/InventoryGUI.java
  game/src/core/components/PlayerComponent.java
  game/src/core/systems/PlayerSystem.java
  game/src/starter/Main.java
Labels: staff:shk, struct:dungeon

#953 [GAME] add unterscheidung von Dateiverarbeitung in IDE und JAR im `DrawComponent`
  game/src/core/components/DrawComponent.java
  game/src/core/utils/components/draw/Animation.java
Labels: staff:wimi, struct:dungeon

#956 [GAME] add levelgraph generator
  dungeon/src/dslToGame/ConvertedGraph.java
  dungeon/src/dslToGame/DotToLevelGraph.java
  game/src/core/level/Room.java
  game/src/core/level/generator/graphBased/graph/GraphGenerator.java
  game/src/core/level/generator/graphBased/graph/LevelGraph.java
  game/src/core/level/levelgraph/DoorDirection.java
  game/src/core/level/levelgraph/GraphLevel.java
  game/src/core/level/levelgraph/GraphLevelGenerator.java
  game/src/core/level/levelgraph/LevelNode.java
  game/src/core/level/room/IRoom.java
  game/src/core/level/room/RoomGenerator.java
  game/test/manual/level/generator/graphBased/GraphGeneratorTest.java
Labels: staff:wimi, struct:dungeon

#955 [DSL] Erweiterung von DSL-Datentypen per Property
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/runtime/AggregatePropertyValue.java
  dsl/src/runtime/EncapsulatedObject.java
  dsl/src/runtime/FuncCallValue.java
  dsl/src/runtime/FunctionValue.java
  dsl/src/runtime/GameEnvironment.java
  dsl/src/runtime/MemorySpace.java
  dsl/src/runtime/PropertyValue.java
  dsl/src/runtime/RuntimeObjectTranslator.java
  dsl/src/runtime/Value.java
  dsl/src/runtime/nativefunctions/NativeFunction.java
  dsl/src/runtime/nativefunctions/NativePrint.java
  dsl/src/semanticanalysis/FunctionDefinitionBinder.java
  dsl/src/semanticanalysis/FunctionSymbol.java
  dsl/src/semanticanalysis/ICallable.java
  dsl/src/semanticanalysis/PropertySymbol.java
  dsl/src/semanticanalysis/SemanticAnalyzer.java
  dsl/src/semanticanalysis/Symbol.java
  dsl/src/semanticanalysis/SymbolTable.java
  dsl/src/semanticanalysis/VariableBinder.java
  dsl/src/semanticanalysis/types/DSLTypeProperty.java
  dsl/src/semanticanalysis/types/IDSLTypeProperty.java
  dsl/src/semanticanalysis/types/TypeBinder.java
  dsl/src/semanticanalysis/types/TypeBuilder.java
  dsl/src/semanticanalysis/types/TypeInstantiator.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/interpreter/TestEnvironment.java
  dsl/test/interpreter/mockecs/ComplexType.java
  dsl/test/interpreter/mockecs/Entity.java
  dsl/test/interpreter/mockecs/TestComponent2.java
  dsl/test/interpreter/mockecs/TestComponentEntityConsumerCallback.java
  dsl/test/interpreter/mockecs/TestComponentTestComponent2ConsumerCallback.java
  dungeon/src/dslToGame/dsltypeproperties/EntityExtension.java
  dungeon/src/dslToGame/taskdsltypes/SingleChoiceDescriptionProperty.java
  dungeon/src/dslToGame/taskdsltypes/SingleChoiceTask.java
Labels: struct:dsl

#968 [GAME] fix DrawComponent for Windows
  game/src/core/components/DrawComponent.java
Labels: bug, struct:dungeon

#969 [GAME] fix Crafting in jar vor mac/unix
  game/src/contrib/crafting/Crafting.java
Labels: bug, struct:dungeon

#930 [DUNGEON] read in DSL-Files per Command Line Argument
  build.gradle
  doc/tasks/anleitung_task_test.md
  dungeon/src/Starter.java
  dungeon/src/dslToGame/DslFileLoader.java
  dungeon/src/dslToGame/DummyDSLFunctions.java
  dungeon/src/dslToGame/loadFiles/DslFileLoader.java
  dungeon/test/dslToGame/TestDslFileLoader.java
  dungeon/test/manual/dslFileReader/DslFileReaderTest.java
  dungeon/test/manual/taskgeneration/TaskGenerationTest.java
  dungeon/test_resources/dslFileLoader/empty.dng
  dungeon/test_resources/dslFileLoader/simple.dng
  dungeon/test_resources/dslFileLoader/test.txt
  dungeon/test_resources/dslFileLoader/testjar.jar
Labels: staff:wimi, struct:dungeon

#961 [GAME] add room based level
  doc/level/room_level.md
  dungeon/src/Starter.java
  dungeon/src/dslToGame/ConvertedGraph.java
  dungeon/src/dslToGame/DotToLevelGraph.java
  dungeon/test/manual/quizquestion/CallbackTest.java
  dungeon/test/manual/taskgeneration/TaskGenerationTest.java
  game/src/contrib/entities/EntityFactory.java
  game/src/core/Game.java
  game/src/core/level/Room.java
  game/src/core/level/TileLevel.java
  game/src/core/level/elements/ILevel.java
  game/src/core/level/generator/graphBased/GraphGenerator.java
  game/src/core/level/generator/graphBased/LevelGraph.java
  game/src/core/level/generator/graphBased/RoomGenerator.java
  game/src/core/level/generator/graphBased/RoombasedLevelGenerator.java
  game/src/core/level/levelgraph/DoorDirection.java
  game/src/core/level/levelgraph/GraphLevel.java
  game/src/core/level/levelgraph/GraphLevelGenerator.java
  game/src/core/level/levelgraph/LevelNode.java
  game/src/core/level/room/IRoom.java
  game/src/core/level/utils/TileTextureFactory.java
  game/src/core/systems/LevelSystem.java
  game/src/starter/Main.java
  game/test/manual/level/generator/graphBased/GraphGeneratorTest.java
Labels: staff:wimi, struct:dungeon

#972 [DSL] Assignment-Expression implementieren
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/semanticanalysis/SemanticAnalyzer.java
  dsl/src/semanticanalysis/VariableBinder.java
  dsl/test/interpreter/TestDSLInterpreter.java
Labels: struct:dsl

#974 [Dungeon] fixed bug in the QuizUI where you could select multiple answers for SC and only one for MC
  dungeon/src/task/quizquestion/QuizDialogDesign.java
Labels: bug, staff:wimi, struct:dungeon

#973 [DUNGEON] add Wizard-Menü Level
  dungeon/src/Starter.java
  game/src/contrib/utils/components/ai/idle/PatrouilleWalk.java
  game/src/contrib/utils/components/ai/idle/StaticRadiusWalk.java
Labels: staff:wimi, struct:dungeon

#981 [DSL] Variablendeklaration implementieren
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/parser/ast/AstVisitor.java
  dsl/src/parser/ast/Node.java
  dsl/src/parser/ast/VarDeclNode.java
  dsl/src/runtime/EncapsulatedObject.java
  dsl/src/runtime/FunctionValue.java
  dsl/src/runtime/IMemorySpace.java
  dsl/src/runtime/MemorySpace.java
  dsl/src/semanticanalysis/SemanticAnalyzer.java
  dsl/src/semanticanalysis/VariableBinder.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/semanticanalysis/TestSemanticAnalyzer.java
Labels: struct:dsl

#980 [GAME] refactor `LevelGraph` and add method to connect `LevelGraph`s
  game/src/core/level/generator/graphBased/LevelGraph.java
  game/src/core/level/generator/graphBased/RoomGenerator.java
  game/src/core/level/generator/graphBased/RoombasedLevelGenerator.java
  game/src/core/level/generator/graphBased/levelGraph/Direction.java
  game/src/core/level/generator/graphBased/levelGraph/GraphGenerator.java
  game/src/core/level/generator/graphBased/levelGraph/LevelGraph.java
  game/src/core/level/generator/graphBased/levelGraph/Node.java
  game/src/core/utils/Tuple.java
  game/test/manual/level/generator/graphBased/GraphGeneratorTest.java
Labels: staff:wimi, struct:dungeon

#984 [GAME] renamed PatrouilleWalk to PatrolWalk
  game/src/contrib/components/AIComponent.java
  game/src/contrib/entities/AIFactory.java
  game/src/contrib/utils/components/ai/idle/PatrolWalk.java
Labels: staff:shk, struct:dungeon

#922 [GAME] Abhängigkeit zwischen den Tests und den Animationsdateien auflösen
  game/test/contrib/systems/HealthSystemTest.java
  game/test/core/systems/VelocitySystemTest.java
  game/test_resources/textures/test_hero/die/knight_m_idle_anim_mirrored_f0.png
  game/test_resources/textures/test_hero/hit/knight_m_idle_anim_mirrored_f0.png
Labels: bug, staff:shk, struct:dungeon

#978 [GAME] add idle animations for knight, fix bug in `VelocitySystem` where wrong idle animation was selected
  game/assets/character/knight/idle_down/idle_down_knight_1.png
  game/assets/character/knight/idle_down/idle_down_knight_2.png
  game/assets/character/knight/idle_left/knight_idle_left_1.png
  game/assets/character/knight/idle_left/knight_idle_left_2.png
  game/assets/character/knight/idle_left/knight_idle_left_3.png
  game/assets/character/knight/idle_left/knight_idle_left_4.png
  game/assets/character/knight/idle_right/knight_idle_right_1.png
  game/assets/character/knight/idle_right/knight_idle_right_2.png
  game/assets/character/knight/idle_right/knight_idle_right_3.png
  game/assets/character/knight/idle_right/knight_idle_right_4.png
  game/assets/character/knight/idle_up/idle_up_knight_1.png
  game/assets/character/knight/idle_up/idle_up_knight_2.png
  game/src/core/components/DrawComponent.java
  game/src/core/systems/VelocitySystem.java
Labels: struct:dungeon

#965 [Game] core.level.utils.LevelUtils#tilesInRange findet Kacheln mehrfach
  game/src/core/level/utils/Coordinate.java
  game/src/core/level/utils/LevelUtils.java
  game/src/core/utils/Point.java
  game/test/core/level/utils/LevelUtilsTest.java
Labels: bug, staff:shk, struct:dungeon

#985 [GAME] make room size base on entities in room
  game/src/core/level/generator/graphBased/RoombasedLevelGenerator.java
Labels: struct:dungeon

#989 [Game] Globale Möglichkeit GUIs mit ESC zu schließen
  game/src/contrib/configuration/KeyboardConfig.java
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/systems/HealthbarSystem.java
  game/src/contrib/systems/HeroUISystem.java
  game/src/core/components/UIComponent.java
Labels: staff:shk, struct:dungeon
