Repository Dungeon-CampusMinden/Dungeon, pull requests merged in 2023-05, with the labels that each got.

#596 [DOC] vereinheitlichen der Namen in /doc
  doc/basics/camera.md
  doc/basics/hud.md
  doc/configuration/config_key.md
  doc/configuration/config_value.md
  doc/configuration/configuration.md
  doc/dsl/interpretation-laufzeit.md
  doc/dsl/interpretation_laufzeit.md
  doc/dsl/readme.md
  doc/dsl/typebuilding.md
  doc/dsl/typsystem.md
  doc/ecs/gameelements/on_death_drop_loot.md
  doc/ecs/gameelements/readme.md
  doc/ecs/readme.md
  doc/graphic/readme.md
  doc/img/animation.gif
  doc/img/move.gif
  doc/img/next-level.gif
  doc/readme.md
Labels: bug, documentation, high prio, WiMi-Dungeon, WiMi-DSL

#554 [GAME] Fix: wait for DeathAnimation onDeath
  game/src/ecs/components/HealthComponent.java
  game/src/ecs/systems/HealthSystem.java
  game/src/ecs/systems/VelocitySystem.java
  game/src/graphic/Animation.java
  game/test/ecs/components/HealthComponentTest.java
  game/test/ecs/systems/HealthSystemTest.java
Labels: bug, struct:dungeon

#560 [GAME] TextureHandler: suche nur in "Dungeon/<build dir>/resources/main/" nach Texturen
  dsl-connector/src/dslToGame/AnimationBuilder.java
  game/assets/.resource_root
  game/src/graphic/textures/TextureHandler.java
  game/src/starter/Game.java
  game/test/graphic/textures/TextureHandlerTest.java
Labels: bug, struct:dungeon

#597 [Game] rename ECS_System into System
  doc/ecs/create_own_content.md
  doc/ecs/img/ai.png
  doc/ecs/img/ai.uxf
  doc/ecs/img/ecs.png
  doc/ecs/img/ecs.uxf
  doc/ecs/img/hitbox.png
  doc/ecs/img/hitbox.uxf
  doc/ecs/img/xpComponent.png
  doc/ecs/img/xpComponent.uxf
  doc/ecs/readme.md
  doc/ecs/structure_design_decisions.md
  doc/img/gameloop.png
  doc/img/gameloop.uxf
  doc/readme.md
  game/src/controller/SystemController.java
  game/src/ecs/systems/AISystem.java
  game/src/ecs/systems/CollisionSystem.java
  game/src/ecs/systems/DrawSystem.java
  game/src/ecs/systems/HealthSystem.java
  game/src/ecs/systems/PlayerSystem.java
  game/src/ecs/systems/ProjectileSystem.java
  game/src/ecs/systems/SkillSystem.java
  game/src/ecs/systems/System.java
  game/src/ecs/systems/VelocitySystem.java
  game/src/ecs/systems/XPSystem.java
  game/src/starter/Game.java
  game/test/ecs/systems/SystemTest.java
Labels: bug, high prio, struct:dungeon

#644 [GAME] add DelayedSet
  game/src/api/utils/DelayedSet.java
  game/src/starter/Game.java
  game/test/api/utils/DelayedSetTest.java
  game/test/ecs/EntityTest.java
  game/test/ecs/components/DropLootTest.java
  game/test/ecs/entities/ChestTest.java
  game/test/ecs/items/ItemDataTest.java
  game/test/ecs/systems/AISystemTest.java
  game/test/ecs/systems/CollisionSystemTest.java
  game/test/ecs/systems/DrawSystemTest.java
  game/test/ecs/systems/HealthSystemTest.java
  game/test/ecs/systems/SkillSystemTest.java
  game/test/ecs/systems/VelocitySystemTest.java
  game/test/ecs/systems/XPSystemTest.java
  game/test/ecs/tools/interaction/InteractionToolTest.java
  game/test/graphic/DungeonCameraTest.java
  game/test/starter/GameTest.java
Labels: staff:wimi, struct:dungeon

#581 [GAME] add Dialog GUI basics to show text and questions
  doc/basics/dialog_window.md
  doc/basics/img/create_nine_patch.png
  doc/basics/img/nine_patch.png
  doc/basics/img/question_with_pic.png
  doc/basics/img/question_with_txt.png
  doc/basics/img/question_with_txt_and_pic.png
  doc/basics/img/skin_composer.png
  doc/basics/img/text_dialog.png
  doc/basics/quiz_dialog.md
  game/assets/image_quiz/dummy.png
  game/assets/skin/myFont.fnt
  game/assets/skin/myFont.png
  game/assets/skin/uiskin.atlas
  game/assets/skin/uiskin.json
  game/assets/skin/uiskin.png
  game/src/ecs/systems/DrawSystem.java
  game/src/ecs/systems/System.java
  game/src/graphic/hud/ButtonGroup.java
  game/src/graphic/hud/DialogDesign.java
  game/src/graphic/hud/EditableText.java
  game/src/graphic/hud/NotEditableText.java
  game/src/graphic/hud/PauseMenu.java
  game/src/graphic/hud/ResponsiveDialogue.java
  game/src/graphic/hud/ScreenImage.java
  game/src/graphic/hud/Scroller.java
  game/src/graphic/hud/TextDialog.java
  game/src/graphic/hud/UITools.java
  game/src/quizquestion/DummyQuizQuestionList.java
  game/src/quizquestion/QuizQuestion.java
  game/src/quizquestion/QuizQuestionContent.java
  game/src/starter/Game.java
  game/src/tools/Constants.java
Labels: struct:documentation, struct:deployment

#574 [DOC] Add docs for Health-, Animation-, AIComponent
  doc/ecs/components/ai_component.md
  doc/ecs/components/animation_component.md
  doc/ecs/components/health_component.md
  doc/ecs/components/hitbox_component.md
  doc/ecs/components/img/aiComponent.png
  doc/ecs/components/img/aiComponent.uxf
  doc/ecs/components/img/animationComponent.png
  doc/ecs/components/img/animationComponent.uxf
  doc/ecs/components/img/healthComponent.png
  doc/ecs/components/img/healthComponent.uxf
  doc/ecs/components/img/hitboxComponent.png
  doc/ecs/components/img/hitboxComponent.uxf
  doc/ecs/components/img/interactionComponent.png
  doc/ecs/components/img/interactionComponent.uxf
  doc/ecs/components/img/inventoryComponent.png
  doc/ecs/components/img/inventoryComponent.uxf
  doc/ecs/components/img/xpComponent.png
  doc/ecs/components/img/xpComponent.uxf
  doc/ecs/components/interaction_component.md
  doc/ecs/components/inventory_component.md
  doc/ecs/components/readme.md
  doc/ecs/components/xp_component.md
  doc/ecs/img/ai.png
  doc/ecs/img/ai.uxf
  game/src/ecs/components/AnimationComponent.java
  game/src/ecs/components/HealthComponent.java
  game/src/ecs/components/ai/AIComponent.java
Labels: struct:documentation, staff:shk

#495 [GAME] add Game Debug Tools
  game/src/configuration/KeyboardConfig.java
  game/src/starter/Game.java
  game/src/tools/Debugger.java
Labels: struct:dungeon

#647 [GAME] fix bug in TileLevelTest.test_findPath_moreThanOnePathPossible
  game/test/level/TileLevelTest.java
Labels: bug, struct:dungeon

#618 [GAME] make Entity final and add EntityFactory
  game/src/content/component_utils/interaction/DropItemsInteraction.java
  game/src/content/entity/EntityFactory.java
  game/src/ecs/components/InteractionComponent.java
  game/src/ecs/components/skill/FireballSkill.java
  game/src/ecs/entities/Entity.java
  game/src/ecs/entities/Hero.java
  game/src/ecs/items/ItemData.java
  game/src/ecs/systems/CollisionSystem.java
  game/src/starter/Game.java
  game/test/ecs/components/AIComponentTest.java
  game/test/ecs/components/AnimationComponentTest.java
  game/test/ecs/components/PlayableComponentTest.java
  game/test/ecs/components/PositionComponentTest.java
  game/test/ecs/components/SkillComponentTest.java
  game/test/ecs/components/VelocityComponentTest.java
  game/test/ecs/entities/ChestTest.java
  game/test/ecs/tools/interaction/InteractionToolTest.java
  game/test/starter/GameTest.java
Labels: struct:documentation, high prio, struct:dungeon

#617 [GAME] merge DesktopLauncher und LibGdxSetup into Game
  build.gradle
  game/src/starter/DesktopLauncher.java
  game/src/starter/Game.java
  game/src/starter/LibgdxSetup.java
  game/src/starter/Main.java
  game/test/controller/LibgdxSetupTest.java
  game/test/mydungeon/DesktopLauncherTest.java
Labels: struct:dungeon

#633 [Game] Gradle Plugins und libs stärker beschränken
  build.gradle
Labels: staff:shk, struct:dungeon

#671 [GAME] add rangeCombat AI
  game/src/contrib/utils/components/ai/fight/RangeAI.java
Labels: struct:dungeon, bounty:5p

#672 [GAME] remove SkillComponent and SkillSystem
  game/src/contrib/components/SkillComponent.java
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/systems/SkillSystem.java
  game/src/contrib/utils/components/skill/Skill.java
  game/src/core/Game.java
  game/test/contrib/components/SkillComponentTest.java
  game/test/contrib/systems/SkillSystemTest.java
  game/test/contrib/systems/SkillTest.java
Labels: bug, staff:shk, struct:dungeon

#678 [Doc] Definiere Reporting-Konzept
  doc/control-mechanisms/reporting.md
  doc/dsl/readme.md
Labels: struct:documentation, staff:wimi, struct:dsl

#674 [GAME] add documentation for skill
  game/src/contrib/components/ProjectileComponent.java
  game/src/contrib/systems/ProjectileSystem.java
  game/src/contrib/utils/components/skill/DamageProjectile.java
  game/src/contrib/utils/components/skill/FireballSkill.java
  game/src/contrib/utils/components/skill/ISkillFunction.java
  game/src/contrib/utils/components/skill/ITargetSelection.java
  game/src/contrib/utils/components/skill/Skill.java
  game/src/contrib/utils/components/skill/SkillTools.java
  game/test/contrib/systems/SkillTest.java
Labels: bug, staff:shk, struct:dungeon

#691 [Doc] Ordnername "control-mechanisms" korrigieren
  doc/control-mechanisms/reporting.md
  doc/control_mechanisms/reporting.md
  doc/tasks/readme.md
Labels: struct:documentation

#692 [GAME] Refactor PlayerComponent
  game/src/contrib/entities/EntityFactory.java
  game/src/core/components/PlayerComponent.java
  game/src/core/systems/PlayerSystem.java
  game/test/core/components/PlayerComponentTest.java
Labels: staff:shk, struct:dungeon

#693 [Doc] Konzept - Datenstrukturen für Aufgabendefinition
  doc/dsl/data_task_definition.md
  doc/dsl/img/replacement_task_entities.png
  doc/dsl/img/replacement_task_entities.uxf
Labels: struct:documentation, staff:wimi, struct:dsl
