Repository Dungeon-CampusMinden/Dungeon, pull requests merged in 2023-07, with the labels that each got.

#796 [DSL] Kontroll-Fluss mit `if` und `else`
  doc/dsl/typsystem.md
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/parser/ast/AstVisitor.java
  dsl/src/parser/ast/BoolNode.java
  dsl/src/parser/ast/ConditionalStmtNodeIf.java
  dsl/src/parser/ast/ConditionalStmtNodeIfElse.java
  dsl/src/parser/ast/FuncDefNode.java
  dsl/src/parser/ast/Node.java
  dsl/src/parser/ast/StmtBlockNode.java
  dsl/src/runtime/GameEnvironment.java
  dsl/src/runtime/Prototype.java
  dsl/src/runtime/Value.java
  dsl/src/semanticanalysis/FunctionCallResolver.java
  dsl/src/semanticanalysis/SemanticAnalyzer.java
  dsl/src/semanticanalysis/VariableBinder.java
  dsl/src/semanticanalysis/types/BuiltInType.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/parser/TestDungeonASTConverter.java
  dsl/test/semanticanalysis/TestSymbolTableParser.java
Labels: struct:dsl

#810 [GAME] add Monsterbuilder to EntityFactory, add AIFactory, add MissingHeroException
  game/src/contrib/entities/AIFactory.java
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/utils/components/skill/SkillTools.java
  game/src/core/Game.java
  game/src/core/utils/MissingHeroException.java
  game/src/starter/Main.java
  game/test/contrib/entities/MonsterTest.java
Labels: staff:shk, struct:dungeon

#816 [GAME] fix asset paths
  game/assets/animation/missing_texture.png
  game/assets/character/monster/chort/idle_left/chort_idle_anim_mirrored_f0.png
  game/assets/character/monster/chort/idle_left/chort_idle_anim_mirrored_f1.png
  game/assets/character/monster/chort/idle_left/chort_idle_anim_mirrored_f2.png
  game/assets/character/monster/chort/idle_left/chort_idle_anim_mirrored_f3.png
  game/assets/character/monster/chort/idle_right/chort_idle_anim_f0.png
  game/assets/character/monster/chort/idle_right/chort_idle_anim_f1.png
  game/assets/character/monster/chort/idle_right/chort_idle_anim_f2.png
  game/assets/character/monster/chort/idle_right/chort_idle_anim_f3.png
  game/assets/character/monster/chort/run_left/chort_run_anim_mirrored_f0.png
  game/assets/character/monster/chort/run_left/chort_run_anim_mirrored_f1.png
  game/assets/character/monster/chort/run_left/chort_run_anim_mirrored_f2.png
  game/assets/character/monster/chort/run_left/chort_run_anim_mirrored_f3.png
  game/assets/character/monster/chort/run_right/chort_run_anim_f0.png
  game/assets/character/monster/chort/run_right/chort_run_anim_f1.png
  game/assets/character/monster/chort/run_right/chort_run_anim_f2.png
  game/assets/character/monster/chort/run_right/chort_run_anim_f3.png
  game/assets/character/monster/imp/idle_left/imp_idle_anim_mirrored_f0.png
  game/assets/character/monster/imp/idle_left/imp_idle_anim_mirrored_f1.png
  game/assets/character/monster/imp/idle_left/imp_idle_anim_mirrored_f2.png
  game/assets/character/monster/imp/idle_left/imp_idle_anim_mirrored_f3.png
  game/assets/character/monster/imp/idle_right/imp_idle_anim_f0.png
  game/assets/character/monster/imp/idle_right/imp_idle_anim_f1.png
  game/assets/character/monster/imp/idle_right/imp_idle_anim_f2.png
  game/assets/character/monster/imp/idle_right/imp_idle_anim_f3.png
  game/assets/character/monster/imp/run_left/imp_run_anim_mirrored_f0.png
  game/assets/character/monster/imp/run_left/imp_run_anim_mirrored_f1.png
  game/assets/character/monster/imp/run_left/imp_run_anim_mirrored_f2.png
  game/assets/character/monster/imp/run_left/imp_run_anim_mirrored_f3.png
  game/assets/character/monster/imp/run_right/imp_run_anim_f0.png
  game/assets/character/monster/imp/run_right/imp_run_anim_f1.png
  game/assets/character/monster/imp/run_right/imp_run_anim_f2.png
  game/assets/character/monster/imp/run_right/imp_run_anim_f3.png
  game/assets/items/Armor/bear_armor.png
  game/assets/items/Armor/chainmail_armor.png
  game/assets/items/Armor/chicken_armor.png
  game/assets/items/Armor/plate_armor.png
  game/assets/items/Health/health_potion16x16.png
  game/assets/items/Health/health_potion18x18.png
  game/assets/items/Letter/letter_16x16.png
  game/assets/items/Letter/letter_18x18.png
  game/assets/objects/Mailbox/mailbox_1.png
  game/assets/objects/Mailbox/mailbox_2.png
  game/assets/skills/fireball/idle_left/fireball_left_1.png
  game/assets/skills/fireball/idle_left/fireball_left_2.png
  game/assets/skills/fireball/idle_left/fireball_left_3.png
  game/assets/skills/fireball/idle_left/fireball_left_4.png
  game/assets/skills/fireball/idle_left/fireball_left_5.png
  game/assets/skills/fireball/idle_left/fireball_left_6.png
  game/assets/skills/fireball/idle_right/fireball_left_1.png
  game/assets/skills/fireball/idle_right/fireball_left_2.png
  game/assets/skills/fireball/idle_right/fireball_left_3.png
  game/assets/skills/fireball/idle_right/fireball_left_4.png
  game/assets/skills/fireball/idle_right/fireball_left_5.png
  game/assets/skills/fireball/idle_right/fireball_left_6.png
  game/src/contrib/configuration/ItemConfig.java
  game/src/contrib/utils/components/item/ItemDataGenerator.java
Labels: bug, staff:shk, struct:dungeon

#817 [GAME] merge painter into drawsystem
  game/src/core/Game.java
  game/src/core/systems/DrawSystem.java
Labels: staff:shk, staff:wimi, struct:dungeon

#792 [GAME] refactor CollideComponent (JavaDoc, Clean Code)
  game/src/contrib/components/CollideComponent.java
Labels: struct:dungeon

#791 [GAME] refactor HealthComponent (JavaDoc, Clean Code)
  game/src/contrib/components/HealthComponent.java
  game/src/contrib/entities/EntityFactory.java
  game/test/contrib/components/HealthComponentTest.java
Labels: struct:dungeon

#766 [GAME] HealthSystem#execute überarbeiten
  game/src/contrib/systems/HealthSystem.java
  game/src/core/components/DrawComponent.java
Labels: bug, staff:shk, struct:dungeon

#824 [GAME] fix bug in EntityFactory
  game/src/contrib/entities/EntityFactory.java
Labels: bug, struct:dungeon

#827 [GAME] refactor CameraComponent (JavaDoc, Clean Code)
  game/src/core/components/CameraComponent.java
Labels: struct:dungeon

#822 [DSL] Ausführung von Funktionsrumpf mit `return`-Statement beenden
  doc/dsl/img/execute_user_defined_function.png
  doc/dsl/img/execute_user_defined_function.uxf
  doc/dsl/img/execute_user_defined_function_setup.png
  doc/dsl/img/execute_user_defined_function_setup.uxf
  doc/dsl/interpretation_laufzeit.md
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/parser/ast/Node.java
  dsl/src/parser/ast/StmtBlockNode.java
  dsl/test/interpreter/TestDSLInterpreter.java
Labels: struct:dsl

#830 [GAME] refactor ProjectileComponent (JavaDoc, Clean Code)
  game/src/contrib/components/ProjectileComponent.java
Labels: struct:dungeon

#832 [GAME] refactor InventoryComponent (JavaDoc, Clean Code)
  game/src/contrib/components/InventoryComponent.java
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/utils/components/health/DropLoot.java
  game/src/contrib/utils/components/interaction/DropItemsInteraction.java
  game/src/contrib/utils/components/item/ItemData.java
  game/test/contrib/components/InventoryComponentTest.java
  game/test/contrib/entities/ChestTest.java
  game/test/contrib/utils/components/item/ItemDataTest.java
Labels: struct:dungeon

#833 [GAME] refactor InteractionComponent (JavaDoc, Clean Code)
  game/src/contrib/components/InteractionComponent.java
  game/test/contrib/components/InteractionComponentTest.java
Labels: struct:dungeon

#843 [GAME] Cause-Entity für Damage-Skills hinzugefügt
  game/src/contrib/utils/components/skill/DamageProjectile.java
  game/src/contrib/utils/components/skill/FireballSkill.java
Labels: bug, staff:shk

#806 [Doc] dokumentation Task im Dungeon und Task-Callbacks hinzugefügt
  doc/control_mechanisms/img/quest.png
  doc/control_mechanisms/img/quest.uxf
  doc/control_mechanisms/readme.md
  doc/control_mechanisms/tasks.md
Labels: struct:documentation

#828 [GAME] refactor XPComponent use Consumer<Entity> for level-up callback ( and JavaDoc, Clean Code)
  game/src/contrib/components/XPComponent.java
  game/src/contrib/systems/XPSystem.java
  game/test/contrib/components/XPComponentTest.java
  game/test/contrib/systems/XPSystemTest.java
Labels: struct:dungeon

#829 [GAME] refactor StatsComponent better api ( and JavaDoc, Clean Code)
  game/src/contrib/components/StatsComponent.java
  game/src/contrib/systems/HealthSystem.java
  game/test/contrib/systems/HealthSystemTest.java
Labels: struct:dungeon

#834 [DSL] `DSLCallback`-Annotation in Typebuilding integrieren
  doc/dsl/typebuilding.md
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/runtime/EncapsulatedObject.java
  dsl/src/runtime/IEvironment.java
  dsl/src/runtime/RuntimeObjectTranslator.java
  dsl/src/semanticanalysis/types/ConsumerFunctionTypeBuilder.java
  dsl/src/semanticanalysis/types/DSLCallback.java
  dsl/src/semanticanalysis/types/FunctionFunctionTypeBuilder.java
  dsl/src/semanticanalysis/types/IFunctionTypeBuilder.java
  dsl/src/semanticanalysis/types/TypeBuilder.java
  dsl/src/semanticanalysis/types/TypeInstantiator.java
  dsl/test/interpreter/mockecs/MockEntityTranslator.java
  dsl/test/interpreter/mockecs/TestComponentWithCallback.java
  dsl/test/interpreter/mockecs/TestComponentWithFunctionCallback.java
  dsl/test/interpreter/mockecs/TestComponentWithTriConsumerCallback.java
  dsl/test/semanticanalysis/types/TestTypeBuilder.java
  dungeon/src/dslToGame/EntityTranslator.java
Labels: struct:dsl

#769 [GAME] refactor `LevelManger` into `LevelSystem`, use `LinkedHashMap` to store Systems in `Game`, use `static Painter` and `static batch` in `DrawSystem`
  game/src/core/Game.java
  game/src/core/LevelManager.java
  game/src/core/level/IOnLevelLoader.java
  game/src/core/systems/DrawSystem.java
  game/src/core/systems/LevelSystem.java
  game/src/starter/Main.java
  game/test/contrib/entities/ChestTest.java
  game/test/contrib/entities/MonsterTest.java
  game/test/contrib/utils/components/interaction/ControlPointReachableTest.java
  game/test/core/level/TileLevelAPITest.java
  game/test/core/systems/CameraSystemTest.java
  game/test/core/systems/VelocitySystemTest.java
Labels: bug, staff:shk, staff:wimi, struct:dungeon

#848 [GAME] add throw of `IllegalArgumentException` to `IPathable#findPath` if `start` or `end` are non-accessible
  game/src/contrib/utils/components/ai/AITools.java
  game/src/contrib/utils/components/ai/fight/RangeAI.java
  game/src/contrib/utils/components/ai/idle/StaticRadiusWalk.java
  game/src/core/Game.java
  game/src/core/level/elements/IPathable.java
  game/src/core/utils/Point.java
  game/test/core/level/TileLevelTest.java
Labels: bug, staff:shk, struct:dungeon

#826 [GAME] implement basic structure for Tasks, addTaskComponents
  dungeon/src/quest/IEvaluable.java
  dungeon/src/quest/Quest.java
  dungeon/src/quest/QuestFactory.java
  dungeon/src/task/PetriNet.java
  dungeon/src/task/Task.java
  dungeon/src/task/TaskComponent.java
  dungeon/src/task/TaskContent.java
  dungeon/src/task/TaskContentComponent.java
Labels: struct:dungeon

#851 [Game] Standardauflösung von Fenster zu 16:9
  game/src/core/Game.java
Labels: staff:shk, struct:dungeon

#861 [GAME] HUD pausiert `LevelSystem` nicht mehr
  game/src/core/systems/LevelSystem.java
Labels: bug, staff:shk, struct:dungeon

#858 [DUNGEON] make `QuizQuestion` extend `Task`
  dungeon/src/quizquestion/QuizQuestion.java
  dungeon/src/quizquestion/QuizQuestionContent.java
  dungeon/src/task/Task.java
  dungeon/src/task/TaskContent.java
  dungeon/src/task/quizquestion/Quiz.java
  dungeon/src/task/quizquestion/QuizDialogDesign.java
  dungeon/src/task/quizquestion/QuizUI.java
  dungeon/test/manual/quizquestion/QuizQuestionUITest.java
Labels: staff:wimi, struct:dungeon

#877 [Game] Fix logging & console spamming
  game/src/contrib/utils/components/draw/AdditionalAnimations.java
  game/src/core/System.java
  game/src/core/components/DrawComponent.java
  game/src/core/utils/components/draw/CoreAnimations.java
Labels: staff:shk, struct:dungeon

#878 [DSL] Rename package CallbackAdapter to callbackadapter
  dsl/src/semanticanalysis/types/TypeBuilder.java
  dsl/src/semanticanalysis/types/TypeInstantiator.java
  dsl/src/semanticanalysis/types/callbackadapter/CallbackAdapter.java
  dsl/src/semanticanalysis/types/callbackadapter/CallbackAdapterBuilder.java
  dsl/src/semanticanalysis/types/callbackadapter/ConsumerFunctionTypeBuilder.java
  dsl/src/semanticanalysis/types/callbackadapter/FunctionFunctionTypeBuilder.java
  dsl/src/semanticanalysis/types/callbackadapter/IFunctionTypeBuilder.java
Labels: struct:dsl

#865 [Game] Merge skins and remove duplicates
  game/assets/items/antidote/antidote_16x16.png
  game/assets/items/antidote/antidote_18x18.png
  game/assets/items/armor/body/bear_armor.png
  game/assets/items/armor/body/chainmail_armor.png
  game/assets/items/armor/body/chicken_armor.png
  game/assets/items/armor/body/pink_armor.png
  game/assets/items/armor/body/plate_armor.png
  game/assets/items/armor/body/undead_armor.png
  game/assets/items/armor/helmet/bear_helmet.png
  game/assets/items/armor/helmet/chainmail_helmet.png
  game/assets/items/armor/helmet/chicken_helmet.png
  game/assets/items/armor/helmet/pink_helmet.png
  game/assets/items/armor/helmet/plate_helmet.png
  game/assets/items/armor/helmet/undead_helmet.png
  game/assets/items/armor/pants/bear_pants.png
  game/assets/items/armor/pants/chainmail_pants.png
  game/assets/items/armor/pants/chicken_pants.png
  game/assets/items/armor/pants/pink_pants.png
  game/assets/items/armor/pants/plate_pants.png
  game/assets/items/armor/pants/undead_pants.png
  game/assets/items/books/letter.png
  game/assets/items/health/health_potion16x16.png
  game/assets/items/health/health_potion18x18.png
  game/assets/items/letter/letter_18x18.png
  game/assets/items/mana/mana_potion_16x16.png
  game/assets/items/mana/mana_potion_18x18.png
  game/assets/items/weapon/fire_sword.png
  game/assets/items/weapon/ice_sword.png
  game/assets/items/weapon/legendary_sword.png
  game/assets/items/weapon/lightning_sword.png
  game/assets/items/weapon/rainbow_sword.png
  game/assets/items/weapon/snake_sword.png
  game/assets/skin/uiskin.atlas
  game/assets/skin/uiskin.json
  game/assets/skin/uiskin.png
Labels: bug, staff:shk, meeting, struct:dungeon

#853 [DSL] Expression-Grammatik
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/parser/ast/AssignmentNode.java
  dsl/src/parser/ast/AstVisitor.java
  dsl/src/parser/ast/ComparisonNode.java
  dsl/src/parser/ast/EqualityNode.java
  dsl/src/parser/ast/FactorNode.java
  dsl/src/parser/ast/LogicAndNode.java
  dsl/src/parser/ast/LogicOrNode.java
  dsl/src/parser/ast/MemberAccessNode.java
  dsl/src/parser/ast/Node.java
  dsl/src/parser/ast/TermNode.java
  dsl/src/parser/ast/UnaryNode.java
  dsl/src/semanticanalysis/FunctionCallResolver.java
  dsl/src/semanticanalysis/SemanticAnalyzer.java
  dsl/src/semanticanalysis/VariableBinder.java
  dsl/src/semanticanalysis/types/TypeBinder.java
  dsl/test/parser/TestDungeonASTConverter.java
Labels: struct:dsl

#873 [DUNGEON] anpassungen an `Quiz.Content` für bessere Bildunterstützung und automatische Typenbestimmung
  dungeon/src/task/quizquestion/Quiz.java
  dungeon/src/task/quizquestion/QuizDialogDesign.java
  dungeon/src/task/quizquestion/UIAnswerCallback.java
  dungeon/test/manual/quizquestion/QuizQuestionUITest.java
  dungeon/test/manual/quizquestion/WizardQuizTest.java
Labels: staff:wimi, struct:dungeon

#879 [DUNGEON] add DSL File input reader
  build.gradle
  dungeon/assets/scripts/input1.dng
  dungeon/src/dslToGame/DslFileLoader.java
  dungeon/src/dslToGame/DummyDSLFunctions.java
  dungeon/test/manual/dslFileReader/DslFileReaderTest.java
Labels: staff:wimi, struct:dungeon

#892 [GAME] Remove console log-handler, make init-logger part of the pre-run configuration.
  dungeon/test/manual/dslFileReader/DslFileReaderTest.java
  dungeon/test/manual/quizquestion/QuizQuestionUITest.java
  dungeon/test/manual/quizquestion/WizardQuizTest.java
  game/src/core/Game.java
  game/src/core/utils/logging/LoggerConfig.java
  game/src/starter/Main.java
Labels: struct:dungeon

#804 [Game] add experiencebar and healthbars for entities
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/hud/heroUI/HeroUITools.java
  game/src/contrib/systems/HealthbarSystem.java
  game/src/contrib/systems/HeroUISystem.java
  game/src/core/Game.java
  game/src/core/System.java
  game/src/core/utils/DelayedSet.java
  game/src/starter/Main.java
Labels: staff:shk, struct:dungeon

#894 [GAME] remove impliziertes registrieren von `System`s beim `Game`
  game/src/core/System.java
  game/test/contrib/entities/ChestTest.java
  game/test/contrib/entities/MonsterTest.java
  game/test/contrib/systems/AISystemTest.java
  game/test/contrib/systems/CollisionSystemTest.java
  game/test/contrib/systems/HealthSystemTest.java
  game/test/contrib/systems/XPSystemTest.java
  game/test/contrib/utils/components/interaction/ControlPointReachableTest.java
  game/test/core/level/TileLevelAPITest.java
  game/test/core/systems/CameraSystemTest.java
  game/test/core/systems/VelocitySystemTest.java
Labels: bug, struct:dungeon

#897 [DSL] Alle Datentypen im TypeBuilder in den globalen Scope einhängen
  dsl/src/runtime/GameEnvironment.java
  dsl/src/runtime/IEvironment.java
  dsl/src/runtime/RuntimeEnvironment.java
  dsl/src/semanticanalysis/Scope.java
  dsl/src/semanticanalysis/types/TypeBuilder.java
  dsl/src/semanticanalysis/types/callbackadapter/ConsumerFunctionTypeBuilder.java
  dsl/src/semanticanalysis/types/callbackadapter/FunctionFunctionTypeBuilder.java
  dsl/src/semanticanalysis/types/callbackadapter/IFunctionTypeBuilder.java
  dsl/test/helpers/Helpers.java
  dsl/test/interpreter/CustomQuestConfigWithListMember.java
  dsl/test/interpreter/CustomQuestConfigWithSetMember.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/interpreter/TestEnvironment.java
  dsl/test/interpreter/mockecs/TestComponentWithListMember.java
  dsl/test/interpreter/mockecs/TestComponentWithSetMember.java
  dsl/test/runtime/TestGameEnvironment.java
  dsl/test/semanticanalysis/TestSymbolTableParser.java
  dsl/test/semanticanalysis/TestTypeBinder.java
  dsl/test/semanticanalysis/types/TestTypeBuilder.java
  dsl/test/semanticanalysis/types/TestTypeInstantiator.java
Labels: struct:dsl

#876 [Game] Replace collision for item pickup with interaction
  dungeon/test/manual/quizquestion/WizardQuizTest.java
  game/src/contrib/components/InteractionComponent.java
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/entities/WorldItemBuilder.java
  game/src/contrib/utils/components/interaction/DropItemsInteraction.java
  game/src/contrib/utils/components/interaction/InteractionTool.java
  game/src/contrib/utils/components/item/ItemData.java
  game/src/core/components/PlayerComponent.java
  game/src/core/utils/Constants.java
  game/src/core/utils/components/draw/Animation.java
  game/test/contrib/components/InteractionComponentTest.java
  game/test/contrib/utils/components/interaction/ControlPointReachableTest.java
  game/test/contrib/utils/components/interaction/InteractionToolTest.java
Labels: staff:shk, struct:dungeon

#740 [GAME] add Crafting Feature (without UI)
  .gitignore
  build.gradle
  dungeon/test/manual/dslFileReader/DslFileReaderTest.java
  dungeon/test/manual/quizquestion/WizardQuizTest.java
  game/assets/items/books/red_book.png
  game/assets/items/potion/water_bottle.png
  game/assets/items/resource/flower_red.png
  game/assets/items/resource/iron_ore.png
  game/assets/items/resource/mushroom_brown.png
  game/assets/items/resource/mushroom_red.png
  game/assets/items/resource/pretzel.png
  game/assets/items/resource/saphire.png
  game/assets/items/resource/stick.png
  game/assets/items/resource/stone.png
  game/assets/recipes/health_potion.recipe
  game/src/contrib/components/InteractionComponent.java
  game/src/contrib/configuration/ItemConfig.java
  game/src/contrib/crafting/Crafting.java
  game/src/contrib/crafting/CraftingIngredient.java
  game/src/contrib/crafting/CraftingResult.java
  game/src/contrib/crafting/CraftingType.java
  game/src/contrib/crafting/InvalidRecipeException.java
  game/src/contrib/crafting/Recipe.java
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/entities/WorldItemBuilder.java
  game/src/contrib/utils/components/interaction/DropItemsInteraction.java
  game/src/contrib/utils/components/interaction/InteractionTool.java
  game/src/contrib/utils/components/item/Item.java
  game/src/contrib/utils/components/item/ItemCategory.java
  game/src/contrib/utils/components/item/ItemData.java
  game/src/contrib/utils/components/item/ItemDataGenerator.java
  game/src/contrib/utils/components/item/ItemType.java
  game/src/core/System.java
  game/src/core/components/PlayerComponent.java
  game/src/core/utils/Constants.java
  game/src/core/utils/components/draw/Animation.java
  game/src/starter/Main.java
  game/test/contrib/components/InteractionComponentTest.java
  game/test/contrib/crafting/CraftingTest.java
  game/test/contrib/utils/components/interaction/ControlPointReachableTest.java
  game/test/contrib/utils/components/interaction/InteractionToolTest.java
  game/test/contrib/utils/components/item/ItemDataTest.java
Labels: staff:shk, struct:dungeon

#909 [DEMO] add how to play
  doc/tasks/anleitung_task_test.md
Labels: staff:wimi

#912 [Game] level generater will no longer place exit
  game/src/core/level/generator/perlinNoise/PerlinNoiseGenerator.java
  game/src/core/level/generator/randomwalk/RandomWalkGenerator.java
Labels: bug, staff:shk, struct:dungeon

#913 [GAME] add transfer function to inventory component
  game/src/contrib/components/InventoryComponent.java
  game/test/contrib/components/InventoryComponentTest.java
Labels: struct:dungeon

#914 Editorconfig: update definitions for Gradle
  .editorconfig
Labels: bug
