Repository Dungeon-CampusMinden/Dungeon, pull requests merged in 2023-02, with the labels that each got.

#182 [GAME] add logic for CollideAI
  game/src/ecs/components/ai/AIComponent.java
  game/src/ecs/components/ai/fight/CollideAI.java
Labels: enhancement, SHK

#203 Add uxf source for typebuilding sequence diagram
  doc/dsl/img/typebuilding.jpg
  doc/dsl/img/typebuilding.uxf
Labels: documentation

#209 [GAME] Cleanup Tests
  game/test/ecs/EntityTest.java
  game/test/ecs/components/AIComponentTest.java
  game/test/ecs/components/AnimationComponentTest.java
  game/test/ecs/components/PlayableComponentTest.java
  game/test/ecs/components/PositionComponentTest.java
  game/test/ecs/components/SkillComponentTest.java
  game/test/ecs/components/SkillTest.java
  game/test/ecs/components/VelocityComponentTest.java
  game/test/ecs/systems/AISystemTest.java
  game/test/ecs/systems/DrawSystemTest.java
  game/test/ecs/systems/ECS_SystemTest.java
  game/test/ecs/systems/VelocitySystemTest.java
Labels: enhancement

#210 [GAME] add names to DSLType(Members)
  game/src/ecs/components/AnimationComponent.java
  game/src/ecs/components/HitboxComponent.java
  game/src/ecs/components/PositionComponent.java
  game/src/ecs/components/VelocityComponent.java
  game/src/ecs/components/ai/AIComponent.java
Labels: enhancement

#206 [CI] add JUnit to CI-Workflow
  .github/workflows/github_ci.yml
Labels: bug

#225 [DSL] Dont crash on unsupported data types
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/runtime/Value.java
  dsl/src/semanticAnalysis/types/TypeInstantiator.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/semanticAnalysis/types/ComponentWithExternalTypeMember.java
  dsl/test/semanticAnalysis/types/ComponentWithInterfaceMember.java
  dsl/test/semanticAnalysis/types/ITestInterface.java
  dsl/test/semanticAnalysis/types/TestTypeBuilder.java
Labels: enhancement

#226 [DSL] Move DSL documentation to doc/dsl/
  doc/dsl/interpretation-laufzeit.md
  doc/dsl/sprachkonzepte.md
  doc/dsl/typebuilding.md
  doc/dsl/typsystem.md
  doc/dsl/ueberblick.md
Labels: documentation

#249 [DSL] Support inline definition of aggregate value in grammar
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/parser/AST/AggregateValueDefinitionNode.java
  dsl/src/parser/AST/AstVisitor.java
  dsl/src/parser/AST/Node.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/semanticAnalysis/SymbolTableParser.java
  dsl/src/semanticAnalysis/types/TypeBinder.java
  dsl/test/interpreter/mockECS/ExternalTypeBuilderMultiParam.java
  dsl/test/parser/TestDungeonASTConverter.java
Labels: enhancement

#269 [DSL] Create `AggregateTypeAdapter` for multi parameter builder methods
  doc/dsl/typebuilding.md
  dsl/src/semanticAnalysis/types/AggregateTypeAdapter.java
  dsl/src/semanticAnalysis/types/DSLTypeMember.java
  dsl/src/semanticAnalysis/types/TypeBuilder.java
  dsl/test/interpreter/mockECS/ExternalTypeBuilderMultiParam.java
  dsl/test/semanticAnalysis/types/TestTypeBuilder.java
Labels: enhancement

#250 [GAME] use .class for Component identification
  game/src/ecs/components/AnimationComponent.java
  game/src/ecs/components/Component.java
  game/src/ecs/components/HitboxComponent.java
  game/src/ecs/components/PlayableComponent.java
  game/src/ecs/components/PositionComponent.java
  game/src/ecs/components/VelocityComponent.java
  game/src/ecs/components/ai/AIComponent.java
  game/src/ecs/components/ai/AITools.java
  game/src/ecs/components/skill/SkillComponent.java
  game/src/ecs/entities/Entity.java
  game/src/ecs/systems/AISystem.java
  game/src/ecs/systems/CollisionSystem.java
  game/src/ecs/systems/DrawSystem.java
  game/src/ecs/systems/KeyboardSystem.java
  game/src/ecs/systems/VelocitySystem.java
  game/src/mydungeon/ECS.java
  game/test/ecs/EntityTest.java
  game/test/ecs/systems/AISystemTest.java
  game/test/ecs/systems/DrawSystemTest.java
  game/test/ecs/systems/VelocitySystemTest.java
Labels: current_week

#202 [GAME] fix velocity system bug
  game/src/ecs/systems/VelocitySystem.java
  game/test/ecs/systems/VelocitySystemTest.java
Labels: bug, current_week

#284 [GAME] changed pathFinished to pathFinishedOrLeft
  game/src/ecs/components/ai/AITools.java
  game/src/ecs/components/ai/idle/RadiusWalk.java
Labels: bug

#278 [GAME] Collision per Strategy Pattern
  game/src/ecs/components/HitboxComponent.java
  game/src/ecs/components/collision/ICollide.java
  game/src/ecs/entities/Hero.java
Labels: SHK, current_week

#277 [GAME] Pause-Menü
  game/src/hud/PauseMenu.java
  game/src/mydungeon/ECS.java
Labels: enhancement, SHK

#287 [DSL] Diagramme für Typadaptierung
  doc/dsl/img/typeadapting.png
  doc/dsl/img/typeadapting.uxf
  doc/dsl/img/typeadapting_complex.png
  doc/dsl/img/typeadapting_complex.uxf
  doc/dsl/img/typebuilding.png
  doc/dsl/img/typebuilding.uxf
  doc/dsl/typebuilding.md
Labels: documentation

#293 [DSL] UML-Diagram für Relation zwischen Adaptertypen und restlichem Typsystem
  doc/dsl/img/adapter_typesystem.png
  doc/dsl/img/adapter_typesystem.uxf
  doc/dsl/typebuilding.md
Labels: documentation

#291 [DSL] Dokumentation von `DSLContext`-Annotationen
  doc/dsl/typebuilding.md
Labels: documentation

#286 [GAME] Healthy Damage: rework strange update-loop in HealthSystem (proof of concept)
  game/src/ecs/components/HealthComponent.java
  game/src/ecs/damage/Damage.java
  game/src/ecs/damage/DamageType.java
  game/src/ecs/systems/HealthSystem.java
  game/src/mydungeon/ECS.java
Labels: question

#350 [DSL] Grammatik für Funktionsdefinitionen erweitern
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/parser/DungeonASTConverter.java
  dsl/test/parser/TestDungeonASTConverter.java
Labels: enhancement

#351 [DSL] AST für Funktionsdefinition erstellen
  dsl/src/parser/AST/AstVisitor.java
  dsl/src/parser/AST/FuncDefNode.java
  dsl/src/parser/AST/Node.java
  dsl/src/parser/AST/ParamDefNode.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/test/parser/TestDungeonASTConverter.java
Labels: enhancement

#245 [GAME] add HealthComponent and HealthSystem
  game/src/ecs/components/HealthComponent.java
  game/src/ecs/components/IOnDeathFunction.java
  game/src/ecs/damage/Damage.java
  game/src/ecs/damage/DamageType.java
  game/src/ecs/systems/HealthSystem.java
  game/src/mydungeon/ECS.java
  game/test/ecs/components/HealthComponentTest.java
  game/test/ecs/systems/HealthSystemTest.java
Labels: current_week

#365 [GAME] Skill Methode per Strategy Pattern
  game/src/ecs/components/ai/fight/MeleeAI.java
  game/src/ecs/components/skill/ISkillFunction.java
  game/src/ecs/components/skill/Skill.java
  game/test/ecs/components/SkillTest.java
Labels: enhancement

#199 [GAME] IIdle: StatischeRadiusWalk
  game/src/ecs/components/ai/AITools.java
  game/src/ecs/components/ai/idle/StaticRadiusWalk.java
Labels: enhancement, SHK, current_week

#387 [GAME] abstract Item
  game/src/ecs/items/Item.java
  game/src/ecs/items/ItemType.java
  game/test/ecs/items/ItemTest.java
Labels: SHK, current_week

#367 [GAME] HitBox-System javadoc
  game/src/ecs/components/HitboxComponent.java
  game/src/ecs/systems/CollisionSystem.java
Labels: bug, documentation

#368 [GAME] ITransition: SelfDefend
  game/src/ecs/components/ai/transition/SelfDefendTransition.java
  game/test/ecs/components/ai/transition/SelfDefendTransitionTest.java
Labels: enhancement, SHK, current_week

#211 [GAME] add ECS Dokumentation
  doc/ecs/components/ai_component.md
  doc/ecs/components/animation_component.md
  doc/ecs/components/health_component.md
  doc/ecs/components/hitbox_component.md
  doc/ecs/components/playable_component.md
  doc/ecs/components/position_component.md
  doc/ecs/components/readme.md
  doc/ecs/components/skill_component.md
  doc/ecs/components/velocity_component.md
  doc/ecs/create_own_content.md
  doc/ecs/ecs_and_strategy_pattern.md
  doc/ecs/img/ai.png
  doc/ecs/img/ai.uxf
  doc/ecs/img/ecs.png
  doc/ecs/img/ecs.uxf
  doc/ecs/readme.md
  doc/ecs/structure_design_decisions.md
  doc/ecs/systems/ai_system.md
  doc/ecs/systems/collision_system.md
  doc/ecs/systems/draw_system.md
  doc/ecs/systems/keyboard_system.md
  doc/ecs/systems/readme.md
  doc/ecs/systems/velocity_system.md
  ecs.md
Labels: documentation, WiMi-Dungeon

#352 [GAME] IIdle: PatrouilleWalk
  game/src/ecs/components/ai/AITools.java
  game/src/ecs/components/ai/idle/PatrouilleWalk.java
Labels: SHK
