Repository Dungeon-CampusMinden/Dungeon, pull requests merged in 2023-03, with the labels that each got.

#448 task documentation erweitern
  doc/tasks/README.md
Labels: documentation, WiMi-Dungeon, WiMi-DSL

#449 Am/doc tasks2
  doc/tasks/README.md
Labels: documentation

#363 [GAME] XPComponent & -System
  doc/ecs/components/readme.md
  doc/ecs/components/xp_component.md
  doc/ecs/img/xpComponent.png
  doc/ecs/img/xpComponent.uxf
  doc/ecs/systems/health_system.md
  doc/ecs/systems/readme.md
  doc/ecs/systems/xp_system.md
  game/src/ecs/components/HealthComponent.java
  game/src/ecs/components/xp/ILevelUp.java
  game/src/ecs/components/xp/XPComponent.java
  game/src/ecs/damage/Damage.java
  game/src/ecs/systems/HealthSystem.java
  game/src/ecs/systems/XPSystem.java
  game/src/starter/Game.java
  game/test/ecs/components/HealthComponentTest.java
  game/test/ecs/components/XPComponentTest.java
  game/test/ecs/systems/HealthSystemTest.java
  game/test/ecs/systems/XPSystemTest.java
Labels: SHK, current_week, Dungeon (Basics)

#388 [GAME] Inventory Component
  doc/ecs/components/inventory_component.md
  doc/ecs/components/readme.md
  doc/ecs/img/inventory.png
  doc/ecs/img/inventory.uxf
  game/src/ecs/components/InventoryComponent.java
  game/src/ecs/items/Item.java
  game/test/ecs/components/InventoryComponentTest.java
Labels: SHK, current_week, Dungeon (Basics)

#443 [GAME] Configuration File
  .gitignore
  doc/configuration/ConfigKey.md
  doc/configuration/ConfigValue.md
  doc/configuration/Configuration.md
  doc/configuration/readme.md
  game/src/configuration/ConfigKey.java
  game/src/configuration/ConfigMap.java
  game/src/configuration/Configuration.java
  game/src/configuration/KeyboardConfig.java
  game/src/configuration/values/ConfigBooleanValue.java
  game/src/configuration/values/ConfigCharValue.java
  game/src/configuration/values/ConfigDoubleValue.java
  game/src/configuration/values/ConfigFloatValue.java
  game/src/configuration/values/ConfigIntValue.java
  game/src/configuration/values/ConfigStringValue.java
  game/src/configuration/values/ConfigValue.java
  game/src/ecs/systems/KeyboardSystem.java
  game/src/starter/Game.java
Labels: SHK, current_week, Dungeon (Advanced)

#400 [GAME] Funktionales Handling von Optionals
  game/src/ecs/systems/AISystem.java
  game/src/ecs/systems/DrawSystem.java
  game/src/ecs/systems/KeyboardSystem.java
  game/src/ecs/systems/VelocitySystem.java
Labels: SHK, Dungeon (Basics)

#396 [GAME] onDeath drop Loot
  doc/ecs/gameelements/onDeathDropLoot
  game/src/ecs/components/DropLoot.java
  game/test/ecs/components/DropLootTest.java
Labels: SHK, current_week, Dungeon (Basics)

#450 [GAME] Items (Active & Passive) + Stats
  game/src/ecs/components/stats/DamageModifier.java
  game/src/ecs/components/stats/StatsComponent.java
  game/src/ecs/items/IItemUse.java
  game/src/ecs/items/ItemActive.java
  game/src/ecs/items/ItemPassive.java
  game/src/ecs/items/ItemType.java
  game/src/ecs/systems/HealthSystem.java
  game/test/ecs/items/ItemActiveTest.java
  game/test/ecs/systems/HealthSystemTest.java
Labels: SHK, current_week, Dungeon (Advanced)

#458 [GAME] fix getRandomTile mögliche Endlosschleife
  game/src/level/elements/ILevel.java
  game/src/level/elements/ITileable.java
  game/test/level/TileLevelTest.java
Labels: bug, SHK, Dungeon (Basics)

#455 [GAME] add Basis Logging
  .gitignore
  game/src/controller/SystemController.java
  game/src/ecs/components/AnimationComponent.java
  game/src/ecs/components/Component.java
  game/src/ecs/components/HealthComponent.java
  game/src/ecs/components/HitboxComponent.java
  game/src/ecs/components/InventoryComponent.java
  game/src/ecs/components/MissingComponentException.java
  game/src/ecs/components/PlayableComponent.java
  game/src/ecs/components/PositionComponent.java
  game/src/ecs/components/VelocityComponent.java
  game/src/ecs/entities/Entity.java
  game/src/ecs/systems/ECS_System.java
  game/src/graphic/Animation.java
  game/src/level/LevelAPI.java
  game/src/logging/CustomLogLevel.java
  game/src/logging/LoggerConfig.java
  game/src/starter/Game.java
Labels: SHK, Dungeon (Basics)

#394 [GAME] add Skill Cool Down
  game/src/ecs/components/skill/Skill.java
  game/test/ecs/components/SkillTest.java
Labels: SHK, WiMi-Dungeon, Dungeon (Basics)

#389 [GAME] add Interaktionssystem & Interaktionscomponent
  doc/ecs/components/interaction_component.md
  doc/ecs/img/interaction.png
  doc/ecs/img/interaction.uxf
  game/src/ecs/components/IInteraction.java
  game/src/ecs/components/InteractionComponent.java
  game/src/ecs/components/ai/AITools.java
  game/src/ecs/systems/KeyboardSystem.java
  game/src/ecs/tools/interaction/ControlPointReachable.java
  game/src/ecs/tools/interaction/IReachable.java
  game/src/ecs/tools/interaction/InteractionData.java
  game/src/ecs/tools/interaction/InteractionTool.java
  game/src/tools/Point.java
  game/test/ecs/components/InteractionComponentTest.java
  game/test/ecs/tools/interaction/ControlPointReachableTest.java
  game/test/ecs/tools/interaction/InteractionToolTest.java
  game/test/testinghelper/SimpleCounter.java
Labels: SHK, current_week, Dungeon (Basics)

#395 [GAME] SkillSystem
  game/src/configuration/KeyboardConfig.java
  game/src/ecs/components/skill/SkillComponent.java
  game/src/ecs/entities/Hero.java
  game/src/ecs/systems/PlayerSystem.java
  game/src/ecs/systems/SkillSystem.java
  game/src/starter/Game.java
  game/test/ecs/systems/SkillSystemTest.java
Labels: SHK, Dungeon (Basics)

#469 [GAME] Add fight skill
  game/src/ecs/components/skill/DamageProjectileSkill.java
  game/src/ecs/components/skill/FireballSkill.java
  game/src/ecs/components/skill/ITargetSelection.java
  game/src/ecs/components/skill/ProjectileComponent.java
  game/src/ecs/components/skill/SkillTools.java
  game/src/ecs/entities/Hero.java
  game/src/ecs/systems/ProjectileSystem.java
  game/src/ecs/systems/VelocitySystem.java
  game/src/starter/Game.java
Labels: SHK

#452 [GAME] Erweiterung des Collision checks um onEnter und onLeave
  doc/ecs/components/hitbox_component.md
  doc/ecs/img/hitbox.png
  doc/ecs/img/hitbox.uxf
  doc/ecs/systems/collision_system.md
  game/src/ecs/components/HitboxComponent.java
  game/src/ecs/components/skill/DamageProjectileSkill.java
  game/src/ecs/entities/Hero.java
  game/src/ecs/items/Item.java
  game/src/ecs/systems/CollisionSystem.java
  game/test/ecs/components/HitboxComponentTest.java
  game/test/ecs/components/SimpleCounter.java
  game/test/ecs/systems/CollisionSystemTest.java
Labels: SHK, current_week

#476 new logo with the red cat in the dimensions 35x35, 64x64 and 128x128
  game/assets/logo/CatLogo_128x128.png
  game/assets/logo/CatLogo_35x35.png
  game/assets/logo/CatLogo_64x64.png
Labels: current_week, Dungeon (Basics), Einsatz und Verbreitung

#478 [GAME] remove old logo files, use new logo
  game/assets/logo/logo128x128.png
  game/assets/logo/logo16x16.png
  game/assets/logo/logo32x32.png
  game/src/tools/Constants.java
Labels: Dungeon (Basics)

#487 use fireball texture for fireball skill
  game/assets/skills/fireball/fireBall_Down/fireBall_Down2.png
  game/assets/skills/fireball/fireBall_Down/fireBall_Down3.png
  game/assets/skills/fireball/fireBall_Down/fireBall_Down4.png
  game/assets/skills/fireball/fireBall_Down/fireBall_Down5.png
  game/assets/skills/fireball/fireBall_Down/fireBall_Down6.png
  game/src/ecs/components/skill/FireballSkill.java
Labels: SHK

#493 [GAME] add better level size generation options
  game/src/level/LevelAPI.java
  game/src/starter/Game.java
  game/test/level/TileLevelAPITest.java
Labels: Dungeon (Basics)

#490 [GAME] Bugs in Skill behoben
  game/src/ecs/components/skill/DamageProjectileSkill.java
  game/src/ecs/components/skill/FireballSkill.java
  game/src/ecs/components/skill/ProjectileComponent.java
  game/src/ecs/components/skill/SkillTools.java
  game/src/ecs/entities/Entity.java
  game/src/ecs/entities/Hero.java
  game/src/ecs/systems/ProjectileSystem.java
  game/src/starter/Game.java
  game/test/ecs/EntityTest.java
  game/test/ecs/entities/ChestTest.java
  game/test/ecs/systems/AISystemTest.java
  game/test/ecs/systems/CollisionSystemTest.java
  game/test/ecs/systems/DrawSystemTest.java
  game/test/ecs/systems/HealthSystemTest.java
  game/test/ecs/systems/SkillSystemTest.java
  game/test/ecs/systems/VelocitySystemTest.java
  game/test/ecs/systems/XPSystemTest.java
  game/test/ecs/tools/interaction/InteractionToolTest.java
Labels: bug, SHK, current_week

#494 [DSL] Gliederung Dokumentation
  doc/dsl/README.md
  doc/dsl/quickstart.md
  doc/dsl/schnittstellen.md
  doc/dsl/sprachkonzepte.md
  doc/dsl/status.md
  doc/dsl/ueberblick.md
Labels: documentation
