Repository Dungeon-CampusMinden/Dungeon, pull requests merged in 2023-04, with the labels that each got.

#525 [GAME] use methods to control the different entity-sets
  doc/ecs/create_own_content.md
  doc/ecs/readme.md
  game/src/ecs/components/skill/DamageProjectileSkill.java
  game/src/ecs/entities/Entity.java
  game/src/ecs/items/Item.java
  game/src/ecs/systems/AISystem.java
  game/src/ecs/systems/CollisionSystem.java
  game/src/ecs/systems/DrawSystem.java
  game/src/ecs/systems/HealthSystem.java
  game/src/ecs/systems/PlayerSystem.java
  game/src/ecs/systems/ProjectileSystem.java
  game/src/ecs/systems/SkillSystem.java
  game/src/ecs/systems/VelocitySystem.java
  game/src/ecs/systems/XPSystem.java
  game/src/ecs/tools/interaction/InteractionTool.java
  game/src/starter/Game.java
  game/test/ecs/EntityTest.java
  game/test/ecs/components/DropLootTest.java
  game/test/ecs/components/HealthComponentTest.java
  game/test/ecs/components/XPComponentTest.java
  game/test/ecs/entities/ChestTest.java
  game/test/ecs/items/ItemTest.java
  game/test/ecs/systems/AISystemTest.java
  game/test/ecs/systems/CollisionSystemTest.java
  game/test/ecs/systems/DrawSystemTest.java
  game/test/ecs/systems/HealthSystemTest.java
  game/test/ecs/systems/SkillSystemTest.java
  game/test/ecs/systems/VelocitySystemTest.java
  game/test/ecs/systems/XPSystemTest.java
  game/test/ecs/tools/interaction/ControlPointReachableTest.java
  game/test/ecs/tools/interaction/InteractionToolTest.java
  game/test/starter/GameTest.java
Labels: SHK, current_week, Dungeon (Basics)

#526 [GAME] make Hero optional
  doc/ecs/components/playable_component.md
  doc/ecs/structure_design_decisions.md
  doc/ecs/systems/keyboard_system.md
  doc/ecs/systems/player_system.md
  doc/ecs/systems/readme.md
  game/src/ecs/components/PlayableComponent.java
  game/src/ecs/components/ai/AITools.java
  game/src/ecs/components/ai/fight/CollideAI.java
  game/src/ecs/components/ai/fight/MeleeAI.java
  game/src/ecs/entities/Hero.java
  game/src/ecs/items/Item.java
  game/src/ecs/systems/PlayerSystem.java
  game/src/starter/Game.java
  game/test/ecs/components/PlayableComponentTest.java
  game/test/ecs/tools/interaction/InteractionToolTest.java
  game/test/starter/GameTest.java
Labels: bug, high prio, SHK, current_week, Dungeon (Basics)

#508 [GAME] add option to freez Animations
  doc/graphic/animation.md
  game/src/ecs/entities/Chest.java
  game/src/graphic/Animation.java
  game/src/graphic/TerminatingAnimation.java
  game/test/graphic/AnimationTest.java
  game/test/graphic/TerminatingAnimationTest.java
Labels: SHK, current_week

#528 [Repo] Rename "CONTRIBUTING.MD" to "CONTRIBUTING.md"
  CONTRIBUTING.md
Labels: bug

#533 [GAME] SkillComponent aus Hero-Klasse entfernt
  game/src/ecs/entities/Hero.java
Labels: bug, SHK, current_week, Dungeon (Basics)

#534 [GAME] Hero aus InteractionTool entfernt
  game/src/ecs/tools/interaction/InteractionTool.java
  game/test/ecs/tools/interaction/InteractionToolTest.java
Labels: bug, SHK, current_week, Dungeon (Basics)

#522 [Game] Tilelevel verhalten aufräumen
  game/src/level/elements/ILevel.java
  game/src/level/elements/ITileable.java
  game/src/level/elements/TileLevel.java
  game/src/level/elements/astar/TileConnection.java
  game/src/level/elements/tile/TileFactory.java
  game/test/level/TileLevelTest.java
  game/test/level/elements/tile/TileFactoryTest.java
Labels: bug, SHK, current_week

#535 [Game] Fix DungeonCamera Tests
  game/src/graphic/DungeonCamera.java
  game/src/starter/Game.java
  game/src/tools/Constants.java
  game/test/graphic/DungeonCameraTest.java
Labels: bug, SHK

#506 [Game] Item refactor to ItemData
  game/src/configuration/ItemConfig.java
  game/src/configuration/values/ConfigEnumValue.java
  game/src/ecs/components/DropLoot.java
  game/src/ecs/components/InventoryComponent.java
  game/src/ecs/components/ItemComponent.java
  game/src/ecs/entities/Chest.java
  game/src/ecs/items/BasicItem.java
  game/src/ecs/items/IOnCollect.java
  game/src/ecs/items/IOnDrop.java
  game/src/ecs/items/IOnUse.java
  game/src/ecs/items/Item.java
  game/src/ecs/items/ItemActive.java
  game/src/ecs/items/ItemData.java
  game/src/ecs/items/ItemDataGenerator.java
  game/src/ecs/items/ItemPassive.java
  game/src/ecs/items/WorldItemBuilder.java
  game/test/ecs/components/DropLootTest.java
  game/test/ecs/components/InventoryComponentTest.java
  game/test/ecs/entities/ChestTest.java
  game/test/ecs/items/ItemActiveTest.java
  game/test/ecs/items/ItemDataTest.java
  game/test/ecs/items/ItemTest.java
Labels: high prio, SHK

#545 [GAME] Add Ctor with default position (PositonComponent)
  game/src/ecs/components/PositionComponent.java
  game/src/ecs/entities/Hero.java
  game/src/level/elements/ILevel.java
  game/src/level/elements/tile/Tile.java
  game/src/starter/Game.java
Labels: Dungeon (Basics)
