Repository Dungeon-CampusMinden/Dungeon, pull requests merged in 2023-01, with the labels that each got.

#115 [GAME] Skill Struktur
  ecs.md
  game/src/ecs/components/AnimationComponent.java
  game/src/ecs/components/AnimationList.java
  game/src/ecs/components/Component.java
  game/src/ecs/components/PlayableComponent.java
  game/src/ecs/components/PositionComponent.java
  game/src/ecs/components/Skill.java
  game/src/ecs/components/SkillComponent.java
  game/src/ecs/components/VelocityComponent.java
  game/src/ecs/entities/Entity.java
  game/src/ecs/entities/Hero.java
  game/src/ecs/systems/AnimationSystem.java
  game/src/ecs/systems/KeyboardSystem.java
  game/src/ecs/systems/System.java
  game/src/ecs/systems/VelocitySystem.java
  game/src/mydungeon/ECS.java
  game/test/ecs/EntityTest.java
  game/test/ecs/components/AnimationComponentTest.java
  game/test/ecs/components/PlayableComponentTest.java
  game/test/ecs/components/PositionComponentTest.java
  game/test/ecs/components/SkillComponentTest.java
  game/test/ecs/components/SkillTest.java
  game/test/ecs/components/VelocityComponentTest.java
  game/test/ecs/systems/DrawSystemTest.java
  game/test/ecs/systems/MovementSystemTest.java
  game/test/ecs/systems/VelocitySystemTest.java
Labels: enhancement

#92 [GAME] Rework current Dungeon-Structure to an ECS
  build.gradle
  ecs.md
  game/src/character/DungeonCharacter.java
  game/src/character/monster/Imp.java
  game/src/character/monster/Monster.java
  game/src/character/objects/Item.java
  game/src/character/objects/Letter.java
  game/src/character/objects/PasswordChest.java
  game/src/character/objects/PasswordInputUI.java
  game/src/character/objects/TreasureChest.java
  game/src/character/player/Hero.java
  game/src/character/skills/BaseMeleeEffect.java
  game/src/character/skills/BaseMeleeSkill.java
  game/src/character/skills/BaseSkill.java
  game/src/character/skills/BaseSkillEffect.java
  game/src/collision/CharacterDirection.java
  game/src/collision/Collidable.java
  game/src/collision/CollisionMap.java
  game/src/collision/Hitbox.java
  game/src/collision/RectCollidable.java
  game/src/collision/TileCollidable.java
  game/src/ecs/components/AnimationComponent.java
  game/src/ecs/components/Component.java
  game/src/ecs/components/PlayableComponent.java
  game/src/ecs/components/PositionComponent.java
  game/src/ecs/components/Skill.java
  game/src/ecs/components/SkillComponent.java
  game/src/ecs/components/VelocityComponent.java
  game/src/ecs/entities/Entity.java
  game/src/ecs/entities/Hero.java
  game/src/ecs/systems/DrawSystem.java
  game/src/ecs/systems/ECS_System.java
  game/src/ecs/systems/KeyboardSystem.java
  game/src/ecs/systems/System.java
  game/src/ecs/systems/SystemController.java
  game/src/ecs/systems/VelocitySystem.java
  game/src/minimap/IMinimap.java
  game/src/minimap/TextMap.java
  game/src/mydungeon/ECS.java
  game/src/mydungeon/Starter.java
  game/src/quest/GraphSearchQuest.java
  game/src/quest/Quest.java
  game/src/quest/QuestFactory.java
  game/test/ecs/EntityTest.java
  game/test/ecs/components/AnimationComponentTest.java
  game/test/ecs/components/PlayableComponentTest.java
  game/test/ecs/components/PositionComponentTest.java
  game/test/ecs/components/SkillComponentTest.java
  game/test/ecs/components/SkillTest.java
  game/test/ecs/components/VelocityComponentTest.java
  game/test/ecs/systems/DrawSystemTest.java
  game/test/ecs/systems/ECS_SystemTest.java
  game/test/ecs/systems/VelocitySystemTest.java
Labels: enhancement

#123 [GAME] Default Component Parameter
  game/src/ecs/components/AnimationComponent.java
  game/src/ecs/components/PositionComponent.java
  game/src/ecs/components/VelocityComponent.java
  game/src/ecs/systems/DrawSystem.java
Labels: enhancement, SHK

#117 [Documentation] Update Readme and co
  CONTRIBUTING.MD
  LICENSE.md
  README.md
Labels: documentation

#130 [GAME] remove hero#getPositionComponent
  game/src/ecs/entities/Hero.java
  game/src/mydungeon/ECS.java
Labels: bug

#135 [DSL->GAME] DSL monster definition prototype
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/runtime/GameEnvironment.java
  dsl/src/runtime/IEvironment.java
  dsl/src/semanticAnalysis/types/AdaptedType.java
  dsl/src/semanticAnalysis/types/AggregateTypeAdapter.java
  dsl/src/semanticAnalysis/types/DSLTypeAdapter.java
  dsl/src/semanticAnalysis/types/IType.java
  dsl/src/semanticAnalysis/types/TypeBuilder.java
  dsl/src/semanticAnalysis/types/TypeInstantiator.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/interpreter/mockECS/ExternalType.java
  dsl/test/interpreter/mockECS/ExternalTypeBuilder.java
  dsl/test/interpreter/mockECS/TestComponentWithExternalType.java
  dsl/test/semanticAnalysis/TestTypeBinder.java
  dsl/test/semanticAnalysis/types/RecordBuilder.java
  dsl/test/semanticAnalysis/types/TestRecordComponent.java
  dsl/test/semanticAnalysis/types/TestRecordUser.java
  dsl/test/semanticAnalysis/types/TestTypeBuilder.java
  dsl/test/semanticAnalysis/types/TestTypeInstantiator.java
  game/src/dslToGame/AnimationBuilder.java
  game/src/ecs/components/AnimationComponent.java
  game/src/ecs/components/PositionComponent.java
  game/src/mydungeon/ECS.java
Labels: enhancement

#145 [DSL] Add support for floating point numbers
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/parser/AST/AstVisitor.java
  dsl/src/parser/AST/DecNumNode.java
  dsl/src/parser/AST/Node.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/runtime/GameEnvironment.java
  dsl/src/runtime/Value.java
  dsl/src/semanticAnalysis/types/BuiltInType.java
  dsl/src/semanticAnalysis/types/TypeBuilder.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/interpreter/mockECS/TestComponent1.java
  dsl/test/semanticAnalysis/TestTypeBinder.java
  dsl/test/semanticAnalysis/types/TestTypeBuilder.java
Labels: enhancement

#137 [GAME] setup velocityComponent for DSL use
  dsl/src/runtime/GameEnvironment.java
  game/src/ecs/components/VelocityComponent.java
  game/src/mydungeon/ECS.java
Labels: bug, enhancement

#128 [GAME] Add Ai-System
  dsl/src/runtime/GameEnvironment.java
  game/src/ecs/components/ai/AIComponent.java
  game/src/ecs/components/ai/AITools.java
  game/src/ecs/components/ai/fight/IFightAI.java
  game/src/ecs/components/ai/fight/MeleeAI.java
  game/src/ecs/components/ai/idle/IIdleAI.java
  game/src/ecs/components/ai/idle/RadiusWalk.java
  game/src/ecs/components/ai/transition/ITransition.java
  game/src/ecs/components/ai/transition/RangeTransition.java
  game/src/ecs/components/skill/Skill.java
  game/src/ecs/components/skill/SkillComponent.java
  game/src/ecs/systems/AISystem.java
  game/src/ecs/systems/VelocitySystem.java
  game/src/mydungeon/ECS.java
  game/test/ecs/components/SkillComponentTest.java
  game/test/ecs/components/SkillTest.java
Labels: enhancement

#154 [GAME] Hitbox Component und System
  dsl/src/runtime/GameEnvironment.java
  game/src/ecs/components/HitboxComponent.java
  game/src/ecs/entities/Hero.java
  game/src/ecs/systems/CollisionSystem.java
  game/src/mydungeon/ECS.java
Labels: enhancement, SHK

#173 [GAME] Add AI-System Tests
  game/src/ecs/components/ai/AIComponent.java
  game/src/ecs/components/ai/AITools.java
  game/src/ecs/components/ai/fight/MeleeAI.java
  game/src/ecs/components/ai/idle/RadiusWalk.java
  game/test/ecs/components/AIComponentTest.java
  game/test/ecs/systems/AISystemTest.java
Labels: bug

#177 [GAME] refactored VelocityComponent
  game/src/ecs/components/VelocityComponent.java
  game/src/ecs/components/ai/AITools.java
  game/src/ecs/entities/Hero.java
  game/src/ecs/systems/KeyboardSystem.java
  game/src/ecs/systems/VelocitySystem.java
  game/test/ecs/components/VelocityComponentTest.java
  game/test/ecs/systems/VelocitySystemTest.java
Labels: bug, documentation

#183 add missingAnimation/Texture to AnimationComponent
  game/assets/animation/missingTexture.png
  game/src/ecs/components/AnimationComponent.java
  game/src/ecs/components/VelocityComponent.java
Labels: enhancement, SHK

#200 [GAME] fix falschen Path abfrage in AITools
  game/src/ecs/components/ai/AITools.java
Labels: bug, SHK
