Repository Dungeon-CampusMinden/Dungeon, pull requests merged in 2023-06, with the labels that each got.

#653 [Doc] Konzept Petri-Netze für Aufgabenabhängigkeiten
  doc/control_mechanisms/img/combined_petri.png
  doc/control_mechanisms/img/combined_petri.uxf
  doc/control_mechanisms/img/conditional_petri.png
  doc/control_mechanisms/img/conditional_petri.uxf
  doc/control_mechanisms/img/mandatory_subtask_petri.png
  doc/control_mechanisms/img/mandatory_subtask_petri.uxf
  doc/control_mechanisms/img/multi_mandatory_subtask_petri.png
  doc/control_mechanisms/img/multi_mandatory_subtask_petri.uxf
  doc/control_mechanisms/img/optional_subtask_petri.png
  doc/control_mechanisms/img/optional_subtask_petri.uxf
  doc/control_mechanisms/img/sequence_petri.png
  doc/control_mechanisms/img/sequence_petri.uxf
  doc/control_mechanisms/petri_nets.md
Labels: struct:documentation, staff:wimi, struct:dsl

#328 [DSL] Doku zu Interpretation und Laufzeit
  doc/dsl/img/aggregate_value_objects.png
  doc/dsl/img/aggregate_value_objects.uxf
  doc/dsl/img/create_component_prototype.png
  doc/dsl/img/create_component_prototype.uxf
  doc/dsl/img/create_prototype.png
  doc/dsl/img/create_prototype.uxf
  doc/dsl/img/imemoryspace_uml.png
  doc/dsl/img/imemoryspace_uml.uxf
  doc/dsl/img/instance_prototype_objects.png
  doc/dsl/img/instance_prototype_objects.uxf
  doc/dsl/img/instantiate_java_class.png
  doc/dsl/img/instantiate_java_class.uxf
  doc/dsl/img/instantiate_prototype.png
  doc/dsl/img/instantiate_prototype.uxf
  doc/dsl/img/interpretation_pipeline.png
  doc/dsl/img/interpretation_pipeline.uxf
  doc/dsl/img/prototype_objects.png
  doc/dsl/img/prototype_objects.uxf
  doc/dsl/img/value_uml.png
  doc/dsl/img/value_uml.uxf
  doc/dsl/interpretation_laufzeit.md
  doc/dsl/readme.md
  doc/dsl/sprachkonzepte.md
  doc/dsl/typebuilding.md
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/runtime/EncapsulatedObject.java
  dsl/src/semanticanalysis/types/TypeInstantiator.java
Labels: struct:documentation

#694 [GAME] Definition der Interfaces
  game/src/contrib/components/AIComponent.java
  game/src/contrib/components/CollideComponent.java
  game/src/contrib/components/HealthComponent.java
  game/src/contrib/components/InteractionComponent.java
  game/src/contrib/components/XPComponent.java
  game/src/contrib/entities/WorldItemBuilder.java
  game/src/contrib/utils/components/ai/IFightAI.java
  game/src/contrib/utils/components/ai/IIdleAI.java
  game/src/contrib/utils/components/ai/ITransition.java
  game/src/contrib/utils/components/ai/fight/CollideAI.java
  game/src/contrib/utils/components/ai/fight/MeleeAI.java
  game/src/contrib/utils/components/ai/fight/RangeAI.java
  game/src/contrib/utils/components/ai/idle/PatrouilleWalk.java
  game/src/contrib/utils/components/ai/idle/RadiusWalk.java
  game/src/contrib/utils/components/ai/idle/StaticRadiusWalk.java
  game/src/contrib/utils/components/ai/transition/RangeTransition.java
  game/src/contrib/utils/components/ai/transition/SelfDefendTransition.java
  game/src/contrib/utils/components/collision/ICollide.java
  game/src/contrib/utils/components/health/DropLoot.java
  game/src/contrib/utils/components/health/IOnDeathFunction.java
  game/src/contrib/utils/components/interaction/ControlPointReachable.java
  game/src/contrib/utils/components/interaction/DropItemsInteraction.java
  game/src/contrib/utils/components/interaction/IInteraction.java
  game/src/contrib/utils/components/interaction/IReachable.java
  game/src/contrib/utils/components/interaction/InteractionTool.java
  game/src/contrib/utils/components/item/IOnCollect.java
  game/src/contrib/utils/components/item/IOnDrop.java
  game/src/contrib/utils/components/item/IOnUse.java
  game/src/contrib/utils/components/item/ItemData.java
  game/src/contrib/utils/components/skill/DamageProjectile.java
  game/src/contrib/utils/components/xp/ILevelUp.java
  game/src/core/utils/TriConsumer.java
  game/test/contrib/components/AIComponentTest.java
  game/test/contrib/components/CollisionComponentTest.java
  game/test/contrib/components/HealthComponentTest.java
  game/test/contrib/components/InteractionComponentTest.java
  game/test/contrib/systems/AISystemTest.java
  game/test/contrib/systems/CollisionSystemTest.java
  game/test/contrib/systems/HealthSystemTest.java
  game/test/contrib/systems/XPSystemTest.java
  game/test/contrib/utils/components/ai/SelfDefendTransitionTest.java
  game/test/contrib/utils/components/health/DropLootTest.java
  game/test/contrib/utils/components/interaction/ControlPointReachableTest.java
  game/test/contrib/utils/components/item/ItemDataTest.java
Labels: staff:shk, struct:dungeon

#700 [Doc] add ItemComponent documentation
  doc/ecs/components/img/item_component.png
  doc/ecs/components/img/item_component.uxf
  doc/ecs/components/item_component.md
  game/src/contrib/components/ItemComponent.java
Labels: struct:documentation

#699 [GAME] Replace DungeonCamera with CameraComponent & CameraSystem
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/systems/DebuggerSystem.java
  game/src/contrib/utils/components/skill/SkillTools.java
  game/src/core/Game.java
  game/src/core/components/CameraComponent.java
  game/src/core/systems/CameraSystem.java
  game/src/core/utils/DungeonCamera.java
  game/src/core/utils/components/draw/Painter.java
  game/test/core/systems/CameraSystemTest.java
  game/test/core/utils/DungeonCameraTest.java
Labels: bug, staff:shk, struct:dungeon

#725 [GAME] Implement ProtectOnAttack
  game/src/contrib/utils/components/ai/transition/ProtectOnAttack.java
  game/test/contrib/utils/components/ai/ProtectOnAttackTest.java
Labels: staff:shk

#710 [GAME] add InventarGUI
  game/assets/items/bone.png
  game/assets/items/leaf.png
  game/assets/items/scroll.png
  game/assets/skin/InventorySkin/inventorySkin.atlas
  game/assets/skin/InventorySkin/inventorySkin.json
  game/assets/skin/InventorySkin/inventorySkin.png
  game/assets/skin/InventorySkin/inventorySlot.png
  game/assets/skin/InventorySkin/myFont.fnt
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/entities/WorldItemBuilder.java
  game/src/contrib/utils/components/item/ItemData.java
  game/src/contrib/utils/components/item/ItemDataGenerator.java
  game/src/core/Game.java
  game/src/core/components/PlayerComponent.java
  game/src/core/hud/Inventory/InventoryDescription.java
  game/src/core/hud/Inventory/InventoryDescriptionListener.java
  game/src/core/hud/Inventory/InventoryGUI.java
  game/src/core/hud/Inventory/InventoryItem.java
  game/src/core/hud/Inventory/InventorySlot.java
  game/src/core/hud/Inventory/InventorySlotClickListener.java
  game/src/core/hud/Inventory/InventorySlotSource.java
  game/src/core/hud/Inventory/InventorySlotTarget.java
  game/src/core/systems/VelocitySystem.java
  game/src/core/utils/Constants.java
Labels: bounty:10p

#731 [Org] rename project "dsl-connector" to "dungeon" in Codeowner configuration
  .github/CODEOWNERS
Labels: bug, high prio

#721 [DSL] Varargs in `load`-Methoden von `IEnvironment` ermöglichen
  dsl/src/runtime/GameEnvironment.java
  dsl/src/runtime/IEvironment.java
  dsl/src/semanticanalysis/types/TypeBinder.java
  dsl/test/helpers/Helpers.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/interpreter/TestEnvironment.java
  dsl/test/semanticanalysis/TestSymbolTableParser.java
  dsl/test/semanticanalysis/TestTypeBinder.java
Labels: struct:dsl

#688 [GAME] add better API for Game
  game/src/contrib/components/CollideComponent.java
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/systems/CollisionSystem.java
  game/src/contrib/systems/DebuggerSystem.java
  game/src/contrib/systems/ProjectileSystem.java
  game/src/contrib/utils/components/ai/AITools.java
  game/src/contrib/utils/components/ai/fight/CollideAI.java
  game/src/contrib/utils/components/ai/fight/MeleeAI.java
  game/src/contrib/utils/components/ai/fight/RangeAI.java
  game/src/contrib/utils/components/ai/idle/PatrouilleWalk.java
  game/src/contrib/utils/components/ai/idle/RadiusWalk.java
  game/src/contrib/utils/components/ai/idle/StaticRadiusWalk.java
  game/src/contrib/utils/components/health/DropLoot.java
  game/src/contrib/utils/components/interaction/ControlPointReachable.java
  game/src/contrib/utils/components/interaction/DropItemsInteraction.java
  game/src/contrib/utils/components/interaction/InteractionTool.java
  game/src/contrib/utils/components/item/ItemData.java
  game/src/contrib/utils/components/skill/DamageProjectile.java
  game/src/core/Game.java
  game/src/core/LevelManager.java
  game/src/core/System.java
  game/src/core/components/PositionComponent.java
  game/src/core/hud/DialogDesign.java
  game/src/core/level/Tile.java
  game/src/core/level/TileLevel.java
  game/src/core/level/elements/ILevel.java
  game/src/core/level/elements/IPathable.java
  game/src/core/level/elements/ITileable.java
  game/src/core/level/elements/astar/TileConnection.java
  game/src/core/level/elements/astar/TileHeuristic.java
  game/src/core/level/levelgraph/GraphLevel.java
  game/src/core/level/room/RoomGenerator.java
  game/src/core/level/utils/TileTextureFactory.java
  game/src/core/systems/CameraSystem.java
  game/src/core/systems/DrawSystem.java
  game/src/core/systems/HudSystem.java
  game/src/core/systems/VelocitySystem.java
  game/src/core/utils/Constants.java
  game/src/core/utils/IVoidFunction.java
  game/src/starter/Main.java
  game/test/contrib/entities/ChestTest.java
  game/test/contrib/systems/AISystemTest.java
  game/test/contrib/systems/CollisionSystemTest.java
  game/test/contrib/systems/HealthSystemTest.java
  game/test/contrib/utils/components/ai/ProtectOnApproachTest.java
  game/test/contrib/utils/components/health/DropLootTest.java
  game/test/contrib/utils/components/interaction/ControlPointReachableTest.java
  game/test/contrib/utils/components/interaction/InteractionToolTest.java
  game/test/core/components/PositionComponentTest.java
  game/test/core/level/TileLevelAPITest.java
  game/test/core/level/TileLevelTest.java
  game/test/core/level/elements/tile/TileFactoryTest.java
  game/test/core/level/generator/PerlinNoiseGeneratorTest.java
  game/test/core/level/generator/RandomWalkGeneratorTest.java
  game/test/core/systems/CameraSystemTest.java
  game/test/core/systems/VelocitySystemTest.java
Labels: staff:wimi, struct:dungeon

#732 [Doc/Publication] add overview table of conferences
  doc/related_work/conferences.md
  doc/related_work/readme.md
Labels: struct:documentation, publication

#741 [GAME] fix bug where LevelManger was initialized two times
  game/src/core/Game.java
Labels: bug, struct:dungeon

#738 [GAME] add `onEntityShow`, `onEntityAdd` and `onEntityRemove` Consumer in `System`
  game/src/core/System.java
  game/test/core/SystemTest.java
Labels: struct:dungeon

#739 [GAME] refactor and move Quiz-UI into the Dungeon-Project, move DummyQuiz into test
  build.gradle
  dungeon/assets/image_quiz/dummy.png
  dungeon/src/quizquestion/DummyQuizQuestionList.java
  dungeon/src/quizquestion/QuizDialogDesign.java
  dungeon/src/quizquestion/QuizQuestionUI.java
  dungeon/test/manual/quizquestion/QuizQuestionUITest.java
  game/src/core/Game.java
  game/src/core/hud/DialogDesign.java
  game/src/core/hud/DialogFactory.java
  game/src/core/hud/QuizQuestionFormatted.java
  game/src/core/hud/UITools.java
  game/src/core/utils/Constants.java
Labels: staff:wimi, struct:dungeon

#676 [GAME] update skill tests
  game/src/contrib/utils/components/skill/Skill.java
  game/test/contrib/systems/SkillTest.java
  game/test/contrib/utils/components/skill/SkillTest.java
Labels: staff:shk

#722 [GAME] rename Entity#getComponent into #fetch and add class cast and throw MissingComponentException if Component is missing, make some classes and method parameter final
  game/src/contrib/components/CollideComponent.java
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/entities/WorldItemBuilder.java
  game/src/contrib/systems/AISystem.java
  game/src/contrib/systems/CollisionSystem.java
  game/src/contrib/systems/DebuggerSystem.java
  game/src/contrib/systems/HealthSystem.java
  game/src/contrib/systems/ProjectileSystem.java
  game/src/contrib/systems/XPSystem.java
  game/src/contrib/utils/components/ai/AITools.java
  game/src/contrib/utils/components/ai/fight/CollideAI.java
  game/src/contrib/utils/components/ai/fight/MeleeAI.java
  game/src/contrib/utils/components/ai/fight/RangeAI.java
  game/src/contrib/utils/components/ai/idle/PatrouilleWalk.java
  game/src/contrib/utils/components/ai/idle/RadiusWalk.java
  game/src/contrib/utils/components/ai/idle/StaticRadiusWalk.java
  game/src/contrib/utils/components/ai/transition/ProtectOnApproach.java
  game/src/contrib/utils/components/ai/transition/ProtectOnAttack.java
  game/src/contrib/utils/components/ai/transition/RangeTransition.java
  game/src/contrib/utils/components/ai/transition/SelfDefendTransition.java
  game/src/contrib/utils/components/health/DropLoot.java
  game/src/contrib/utils/components/interaction/ControlPointReachable.java
  game/src/contrib/utils/components/interaction/DropItemsInteraction.java
  game/src/contrib/utils/components/interaction/InteractionTool.java
  game/src/contrib/utils/components/item/ItemData.java
  game/src/contrib/utils/components/skill/DamageProjectile.java
  game/src/core/Entity.java
  game/src/core/Game.java
  game/src/core/level/elements/IPathable.java
  game/src/core/level/elements/ITileable.java
  game/src/core/systems/CameraSystem.java
  game/src/core/systems/DrawSystem.java
  game/src/core/systems/HudSystem.java
  game/src/core/systems/PlayerSystem.java
  game/src/core/systems/VelocitySystem.java
  game/src/core/utils/components/MissingComponentException.java
  game/test/contrib/components/CollisionComponentTest.java
  game/test/contrib/components/InteractionComponentTest.java
  game/test/contrib/entities/ChestTest.java
  game/test/contrib/utils/components/ai/ProtectOnAttackTest.java
  game/test/contrib/utils/components/ai/SelfDefendTransitionTest.java
  game/test/contrib/utils/components/health/DropLootTest.java
  game/test/contrib/utils/components/interaction/InteractionToolTest.java
  game/test/contrib/utils/components/item/ItemDataTest.java
  game/test/core/EntityTest.java
Labels: high prio, staff:wimi

#748 [DOC] Ergänzungen zu der Konferenzliste
  doc/related_work/conferences.md
Labels: struct:documentation

#736 [DSL] Rückgabewert und Interpretation von nutzerdefinierten Funktionen
  doc/dsl/img/execute_user_defined_function.png
  doc/dsl/img/execute_user_defined_function.uxf
  doc/dsl/interpretation_laufzeit.md
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/parser/ast/AstVisitor.java
  dsl/src/parser/ast/Node.java
  dsl/src/parser/ast/ReturnStmtNode.java
  dsl/src/runtime/GameEnvironment.java
  dsl/src/runtime/IEvironment.java
  dsl/src/runtime/RuntimeEnvironment.java
  dsl/src/semanticanalysis/FunctionCallResolver.java
  dsl/src/semanticanalysis/FunctionSymbol.java
  dsl/src/semanticanalysis/SemanticAnalyzer.java
  dsl/src/semanticanalysis/types/TypeBuilder.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/interpreter/TestFunctionReturnHelloWorld.java
  dsl/test/parser/TestDungeonASTConverter.java
  dsl/test/runtime/TestGameEnvironment.java
  dsl/test/semanticanalysis/TestSymbolTableParser.java
  dsl/test/semanticanalysis/types/TestFunctionType.java
Labels: struct:dsl

#750 [Game][Dungeon] fix Dialog style
  dungeon/src/quizquestion/QuizDialogDesign.java
  dungeon/src/quizquestion/QuizQuestionUI.java
  game/assets/skin/uiskin.json
  game/src/core/hud/DialogDesign.java
  game/src/core/hud/DialogFactory.java
  game/src/core/hud/UITools.java
Labels: bug, staff:shk, struct:dungeon

#761 [Game] Hero ohne PositionComponent führt nicht mehr zu MissingComponentException
  game/src/core/Game.java
  game/src/core/utils/components/MissingComponentException.java
Labels: bug, staff:shk

#711 [GAME] add HeroUI
  game/assets/hud/healthBar/healthBar_1.png
  game/assets/hud/healthBar/healthBar_2.png
  game/assets/hud/healthBar/healthBar_3.png
  game/assets/hud/healthBar/healthBar_4.png
  game/assets/hud/healthBar/healthBar_5.png
  game/assets/hud/healthBar/healthBar_6.png
  game/assets/hud/healthBar/healthBar_7.png
  game/assets/hud/xpBar/xpBar_1.png
  game/assets/hud/xpBar/xpBar_2.png
  game/assets/hud/xpBar/xpBar_3.png
  game/assets/hud/xpBar/xpBar_4.png
  game/assets/hud/xpBar/xpBar_5.png
  game/assets/hud/xpBar/xpBar_6.png
  game/assets/hud/xpBar/xpBar_7.png
  game/assets/skin/DungeonFont.ttf
  game/assets/skin/enemyHealthBar/enemyHealthBar.atlas
  game/assets/skin/enemyHealthBar/enemyHealthBar.json
  game/assets/skin/enemyHealthBar/enemyHealthBar.png
  game/src/contrib/components/HealthComponent.java
  game/src/contrib/components/XPComponent.java
  game/src/contrib/entities/EntityFactory.java
  game/src/contrib/utils/components/skill/DamageProjectile.java
  game/src/contrib/utils/components/skill/SkillTools.java
  game/src/core/Game.java
  game/src/core/hud/ScreenImage.java
  game/src/core/hud/heroUI/EnemyHealthBar.java
  game/src/core/hud/heroUI/HeroHealthBar.java
  game/src/core/hud/heroUI/HeroUI.java
  game/src/core/hud/heroUI/HeroXPBar.java
  game/src/core/utils/Constants.java
Labels: bounty:10p

#763 [GAME] ProjectileSystem execute verbessern
  game/src/contrib/systems/ProjectileSystem.java
Labels: staff:shk, struct:dungeon

#755 [GAME] refactor PositionComponent (JavaDoc, Clean Code)
  game/src/core/components/PositionComponent.java
Labels: struct:documentation, struct:dungeon

#758 [GAME] refactor PlayerComponent (JavaDoc, Clean Code)
  game/src/contrib/entities/EntityFactory.java
  game/src/core/components/PlayerComponent.java
  game/test/core/components/PlayerComponentTest.java
Labels: struct:documentation, struct:dungeon

#753 [GAME] CollisionSystem execute stream verbessern
  game/src/contrib/systems/CollisionSystem.java
Labels: staff:shk, struct:dungeon

#497 [DOC] add Klassen- und Sequenzdiagramm für das Itemkonzept
  doc/ecs/item/klassendiagram.png
  doc/ecs/item/klassendiagram.uxf
  doc/ecs/item/sequenzdiagramm.png
  doc/ecs/item/sequenzdiagramm.uxf
Labels: struct:documentation

#770 [GAME] Entity#toString will return $name_$id if the entity has a name
  game/src/core/Entity.java
Labels: struct:dungeon

#774 [DSL] Refactoring von DSLInterpreter tests
  dsl/test/helpers/Helpers.java
  dsl/test/interpreter/TestDSLInterpreter.java
Labels: struct:dsl

#777 [Game] Entity Comparable<Entity> implemented
  game/src/contrib/systems/CollisionSystem.java
  game/src/core/Entity.java
  game/test/core/EntityTest.java
Labels: staff:shk, struct:dungeon

#729 [DSL] DSL-Typ `entity` mit Java-Klasse `Entity` verknüpfen; Instanziierung von EntityTypen (`entity_type`) explizit durch Funktion ausführen
  doc/dsl/interpretation_laufzeit.md
  doc/dsl/status.md
  doc/dsl/typebuilding.md
  dsl/src/antlr/DungeonDSL.g4
  dsl/src/interpreter/DSLInterpreter.java
  dsl/src/parser/DungeonASTConverter.java
  dsl/src/parser/ast/AstVisitor.java
  dsl/src/parser/ast/Node.java
  dsl/src/parser/ast/PrototypeDefinitionNode.java
  dsl/src/runtime/GameEnvironment.java
  dsl/src/runtime/Prototype.java
  dsl/src/runtime/Value.java
  dsl/src/runtime/nativefunctions/NativeInstantiate.java
  dsl/src/semanticanalysis/SemanticAnalyzer.java
  dsl/src/semanticanalysis/types/BuiltInType.java
  dsl/src/semanticanalysis/types/TypeBinder.java
  dsl/test/interpreter/TestDSLInterpreter.java
  dsl/test/interpreter/TestEnvironment.java
  dsl/test/interpreter/mockecs/Entity.java
  dsl/test/parser/TestDungeonASTConverter.java
  dsl/test/semanticanalysis/TestSymbolTableParser.java
  dsl/test/semanticanalysis/TestTypeBinder.java
  game/src/core/Entity.java
Labels: struct:dsl

#756 [GAME] remove DrawComponent from the entity if animations can't be loaded and refactor the DrawComponent (JavaDoc, Clean Code)
  game/src/core/components/DrawComponent.java
Labels: struct:documentation, struct:dungeon

#779 [Doc] Grafik für Zusammenhang der Projekt-Bausteine zu Doku hinzufügen
  doc/dsl/dsl_zu_level.md
  doc/dsl/img/system_overview.png
  doc/dsl/img/system_overview.uxf
  doc/dsl/readme.md
  doc/dsl/schnittstellen.md
Labels: struct:documentation

#772 [Doc] dokumentiere Austausch mit Projekt-Teams
  doc/related_work/partner.md
Labels: struct:documentation

#784 [GAME] add component stream getter to `Entity`
  game/src/core/Entity.java
Labels: struct:dungeon

#785 [GAME] refactor AIComponent (JavaDoc, Clean Code)
  game/src/contrib/components/AIComponent.java
  game/test/contrib/components/AIComponentTest.java
  game/test/contrib/systems/AISystemTest.java
  game/test/contrib/utils/components/ai/ProtectOnApproachTest.java
  game/test/contrib/utils/components/ai/ProtectOnAttackTest.java
Labels: struct:dungeon

#793 [Game] improve hudsystem using new addEntity and removeEntity Observers
  game/src/core/systems/HudSystem.java
Labels: staff:shk, struct:dungeon

#798 [GAME] Fix stretching on window rescale + Add Fullscreen
  game/src/core/Game.java
  game/src/core/configuration/KeyboardConfig.java
  game/src/core/systems/CameraSystem.java
  game/src/starter/Main.java
Labels: bug, staff:shk
