Repository Dungeon-CampusMinden/Dungeon, pull requests merged in 2024-01, with the labels that each got.

#1318 tooling: remove checkstyle from project
  .github/workflows/github_ci.yml
  build.gradle
  checks.xml
  config/checkstyle/suppressions.xml
  doc/wiki/code-conventions.md
Labels: bug, dungeon, github_actions

#1319 doc: fix broken markdown
  doc/wiki/code-conventions.md
Labels: bug

#1320 tool: remove spotbugs
  build.gradle
  doc/wiki/code-conventions.md
Labels: dungeon, github_actions

#1322 Cleanup Gradle Config: Vereinheitliche Definition der Variablen und Dependencies
  build.gradle
Labels: bug, tooling

#1348 Gradle Config: Dependabot Expansion
  .github/dependabot.yml
  build.gradle
  dependencies.gradle
Labels: tooling

#1353 CI: run JUnit@Linux always, and @Mac/@Win only if tests changed
  .github/workflows/github_ci.yml
Labels: bug, tooling

#1357 Gradle: remove superfluous repositories
  build.gradle
Labels: bug, tooling

#1358 Gradle: simplify recognition of macOS
  build.gradle
Labels: tooling

#1362 Dependabot: disable all labels
  .github/dependabot.yml
Labels: bug, tooling

#1364 Dependabot: fix indentation introduced in #1348: go back to two spaces intentation
  .github/dependabot.yml
Labels: bug, tooling

#1367 Rename organisation: use 'Dungeon-CampusMinden' instead of 'Programmiermethoden'
  CITATION.cff
  README.md
  blockly/doc/installation.md
  blockly/doc/introduction.md
  doc/wiki/faq.md
  doc/wiki/how-to-dokumentation.md
  dungeon/doc/dsl/dsl_zu_level.md
  dungeon/doc/dsl/interpretation_laufzeit.md
  dungeon/doc/dsl/typsystem.md
  dungeon/doc/level/room_level.md
  dungeon/doc/quickstart.md
  dungeon/doc/readme.md
  dungeon/src/contrib/components/ProjectileComponent.java
  dungeon/src/dsl/runtime/memoryspace/EncapsulatedObject.java
  dungeon/src/graph/petrinet/PetriNet.java
  dungeon/src/graph/petrinet/PetriNetFactory.java
  dungeon/test/dsl/interpreter/TestDSLInterpreter.java
  game/doc/quickstart.md
Labels: bug
